### ISSUE TITLE
支持 Midjourney 图生图和 Actions 中文可读化

### ISSUE THREAD

**Issue by kokojacket** [Deeptrain-Community/chatnio#100]
1、希望支持图生图，
2、以及建议mj生图选项中文化便于普通用户一眼识别

**Comment by zmh-program** [comment]
![831cca693665a94771311f556031826b](https://github.com/Deeptrain-Community/chatnio/assets/112773885/9a158278-278b-4d5a-8595-02b73e0092b2)
![831cca693665a94771311f556031826b](https://github.com/Deeptrain-Community/chatnio/assets/112773885/86733086-f95f-4c54-871e-1afc92322c66)

**Comment by zmh-program** [comment]
midjourney proxy 无外部图的图生图功能
