### ISSUE TITLE
渠道支持单独自定义代理 (SOCKS5/HTTPPROXY/HTTPSPROXY)

### ISSUE THREAD

**Issue by jiusheng6** [Deeptrain-Community/chatnio#101]
有些渠道是需要特定地区的，希望支持单独设置http，或者socks5。

**Comment by zmh-program** [comment]
![image](https://github.com/Deeptrain-Community/chatnio/assets/112773885/d6d27ad3-f874-4563-b3ca-1732ac78cfb1)
