### ISSUE TITLE
建议模型市场支持单独展开编辑模式而不是全展开，全展开也可以保留用于查看。

### ISSUE THREAD

**Issue by kokojacket** [Deeptrain-Community/chatnio#105]
![Clip_2024-03-11_21-03-23](https://github.com/Deeptrain-Community/chatnio/assets/74887370/6bee9837-ad93-49a1-b3c4-f5fa952e69fc)

**Comment by zmh-program** [comment]
已支持在模型市场管理中对特定模型的折叠和展开操作

在全部展开的情况下折叠模型：
![d6c9c8bd82979857a823d50e32c0a940](https://github.com/Deeptrain-Community/chatnio/assets/112773885/b99e3dcc-7558-43cf-91ef-fbe80d33c081)

在全部折叠的情况展开模型：
![a5873a67e8990e348b8e8a47363dc32e](https://github.com/Deeptrain-Community/chatnio/assets/112773885/dcc021c6-0563-423b-b479-463d6bfdbc28)
