### ISSUE TITLE
期望支持emoji显示

### ISSUE THREAD

**Issue by kokojacket** [Deeptrain-Community/chatnio#106]
![image](https://github.com/Deeptrain-Community/chatnio/assets/74887370/60f3c5f6-b675-4195-9863-527d0b1926e0)
![image](https://github.com/Deeptrain-Community/chatnio/assets/74887370/f7285a2d-7180-4c66-8124-1ed7ff9b40c0)

**Comment by zmh-program** [comment]
![Screenshot_20240312_091505_edit_98273616481209.jpg](https://github.com/Deeptrain-Community/chatnio/assets/112773885/98ce5557-c5ac-4244-a904-3ed05172be50)
