### ISSUE TITLE
GPT-3.5-16K 异常要求 Quota

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Deeptrain-Community/chatnio#11]
![image](https://github.com/Deeptrain-Community/chatnio/assets/109946426/3510912f-94c2-4350-bbc1-3d4e37176afa)
3.5-16K 现在不 free 了？

**Comment by JingHai-Lingyun** [comment]
草 又好了 奇怪

**Comment by zmh-program** [comment]
已知问题，鉴权在登录前发送，即匿名状态。因成本问题，非登录无法使用 GPT-3.5-16K，其他模型亦如此。

**Comment by JingHai-Lingyun** [comment]
额 等下 是这样的
在未登录的情况下，首次登录之后需要刷新页面才能使用 GPT-3.5-16K

**Comment by zmh-program** [comment]
符合已知问题逻辑。鉴权时 websocket 连接读取 localStorage 为空。
所以第一次登录之后 此次连接仍然为匿名状态鉴权，因而提示此消息。

**Comment by zmh-program** [comment]
此问题已经修复 #38dad63
