### ISSUE TITLE
call function array 失败

### ISSUE THREAD

**Issue by kanglang6226xi** [Deeptrain-Community/chatnio#110]
lobe_chat中使用steam插件call function时报错
{
  "error": {
    "message": "Invalid schema for function 'steam____featuredApps': None is not of type 'array'. (type: invalid_request_error)",
    "type": "chatnio_api_error"
  },
  "endpoint": "https://****.com/v1",
  "provider": "openai"
}

**Comment by zmh-program** [comment]
已修复。如果还出现类似于 LobeChat 的 None 的无效参数传递，请 reopen 此 issue
