### ISSUE TITLE
选择其他模型，重新回答时还是用的之前的模型

### ISSUE THREAD

**Issue by ilay1678** [Deeptrain-Community/chatnio#113]
希望能像NextChat那样，重新回答时使用当前选择的模型

**Comment by zmh-program** [comment]
可以的

**Comment by kokojacket** [comment]
@zmh-program 类似，使用他人分享的会话消息，是否应该自动跳转为他人原本使用的会话模型
![image](https://github.com/Deeptrain-Community/chatnio/assets/74887370/72794e3c-66b7-4765-9d8b-67cade227b0a)

![image](https://github.com/Deeptrain-Community/chatnio/assets/74887370/c2a85467-bf4a-4c87-8f27-1765b0ff5dee)

**Comment by zmh-program** [comment]
> @zmh-program 类似，使用他人分享的会话消息，是否应该自动跳转为他人原本使用的会话模型 ![image](https://private-user-images.githubusercontent.com/74887370/312350773-72794e3c-66b7-4765-9d8b-67cade227b0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTgxOTEsIm5iZiI6MTcxMDMxNzg5MSwicGF0aCI6Ii83NDg4NzM3MC8zMTIzNTA3NzMtNzI3OTRlM2MtNjZiNy00NzY1LTlkOGItNjdjYWRlMjI3YjBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA4MTgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzYTQ2OGIzYjc0ODQwNmIwODczNGM4MTJkYjFhNDdiNDBjYjUxMGJmMTMzNTgyZjFhZGJkNWQ2YzRlMzY4YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pxUYFpIN4DXZMwf3A2AtbbDuydZl_9ty3MgbDBHpo8s)
> 
> ![image](https://private-user-images.githubusercontent.com/74887370/312350700-c2a85467-bf4a-4c87-8f27-1765b0ff5dee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTgxOTEsIm5iZiI6MTcxMDMxNzg5MSwicGF0aCI6Ii83NDg4NzM3MC8zMTIzNTA3MDAtYzJhODU0NjctYmY0YS00Yzg3LThmMjctMTc2NWIwZmY1ZGVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA4MTgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiZTMyM2ZkMzM3MDRlY2Q2NWQ1ZWI1OTg0NjQxYTRhNjZlMGJiYWI3YzkwZTg5NmI2YThhM2M4NDRhZTY3ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cYj3yaX9R4yi2L7UXD9BYSo6Hj4DV0r1yX5JzxYpRGA)

@kokojacket 另起issue

**Comment by zmh-program** [comment]
已支持
