### ISSUE TITLE
适配文心一言 ERNIE Bot

### ISSUE THREAD

**Issue by kanglang6226xi** [Deeptrain-Community/chatnio#114]
希望增加模型适配：

文本理解：ERNIE 4.0、ERNIE 3.5、ERNIE Tiny、ERNIE Speed
文生图：文心一格、Stable-Diffusion-XL（百度版）

API Doc：https://cloud.baidu.com/doc/WENXINWORKSHOP/s/flfmc9do2
![image](https://github.com/Deeptrain-Community/chatnio/assets/160992138/0432cdac-f347-4213-9e7a-86f595f5d4aa)

**Comment by zmh-program** [comment]
reopen #31

**Comment by Itsmejp333** [comment]
-

**Comment by zmh-program** [comment]
transfer to #222
