### ISSUE TITLE
建议增加openrouter.ai渠道

### ISSUE THREAD

**Issue by Tuanzi1015** [Deeptrain-Community/chatnio#122]
openrouter.ai 用的还是比较多的，建议兼容一下

**Comment by zmh-program** [comment]
我看上文所述openrouter是兼容openai格式的
![Screenshot_20240314_155407_edit_28760251072082.jpg](https://github.com/Deeptrain-Community/chatnio/assets/112773885/f3732c5e-e237-441b-bc61-3436ef68677d)

**Comment by zmh-program** [comment]
测试了一下 确实可以连通 无需进行代码的改动

接入点填 `https://openrouter.ai/api`
模型填 `openai/gpt-3.5-turbo`
