### ISSUE TITLE
绘画同时发送放大或者变换问题

### ISSUE THREAD

**Issue by jiusheng6** [Deeptrain-Community/chatnio#123]
![image](https://github.com/Deeptrain-Community/chatnio/assets/67815745/960b12ef-cabe-4ff2-9419-2c0aab6c6929)

**Comment by zmh-program** [comment]
已修复，其他操作正在执行时将变为：
![image](https://github.com/Deeptrain-Community/chatnio/assets/112773885/c51d2707-a932-420c-8415-a664b0700255)
