### ISSUE TITLE
运行缓慢

### ISSUE THREAD

**Issue by GeekHank** [Deeptrain-Community/chatnio#13]
很好的平台，但是到了晚上会出现运行异常缓慢问题，怀疑API滥用，希望能够加入限制，更好的活下去！

**Comment by zmh-program** [comment]
感谢但是此为香港 CN2 线路被打，不是我们的问题，154段全链出现此问题，同时这更不像需要在Github Issue中需要提出的问题，IP 节流策略已有成熟的体系。
