### ISSUE TITLE
自定义Gmail邮箱域名的SMTP测试发件失败

### ISSUE THREAD

**Issue by siwei-s** [Deeptrain-Community/chatnio#133]
## 配置
发件域名： `smtp.gmail.com`
SMTP端口：`587`
用户名：`xxx@gmail.com`
密码：`app_password_insecure`
发件人：`yyy@my_domain.com` （我绑定自己域名的一个邮箱，之前配置其他SMTP也用过，是可以用的）

始终返回“请求失败... Username and password not accepted ...”

## 问题
1. 系统设置总是提醒*"SMTP 发件参数未正确配置，已禁用邮箱验证"*，这是符合预期的吗？好像前端检测到"@"字符就会报错，且用户名的输入框红色高亮
2. 密码应该填我gmail登录密码还是应用密码？我两个都尝试了，都会报错。我确定应用密码没有问题，因为其他SMTP可以用

**Comment by zmh-program** [comment]
是的，用户名不需要加@以及后面的域名邮箱名称，发件人才需要

比如 想用 `postmaster@example.com` 发件：
用户名：`postmaster`
发件人：`postmaster@example.com`

**Comment by zmh-program** [comment]
我一般是用腾讯云ses发件，没太了解过 gmail 的 smtp

我不太清楚上文的自定义域名，是指将gmail转发至你的域名邮箱？

试试设置用户名为 yyy, 发件域名为 yourdomain

**Comment by zmh-program** [comment]
OK
