### ISSUE TITLE
请问下项目中是怎么做前端静态文件部署的？

### ISSUE THREAD

**Issue by B1ackg0d** [Deeptrain-Community/chatnio#136]
Hello靓仔，这是一个非常棒的开源项目！目前我正常在学习该项目的部署和实施。按照自定义安装中，前端`pnpm build`打包后到dist目录。这时候启动后端。想请问下我在后端代码中没看到类似gin的Static或StaticFS这样的方法来服务静态文件，是用的其他方法来设置的吗？
![image](https://github.com/Deeptrain-Community/chatnio/assets/50610732/d246ffd8-052c-4772-919c-b47bf024d4ab)
文档里提到这个，也没有在代码中看到。提前感谢你的解答~

**Comment by zmh-program** [comment]
https://github.com/Deeptrain-Community/chatnio/blob/aefe8a06ee712f59782056b4744ef09dbbad902b/utils/config.go#L151-L154

**Comment by B1ackg0d** [comment]
感谢~忽然发现我是四个月前拉的项目，一直没有更新代码QAQ
