### ISSUE TITLE
分享管理显示错误

### ISSUE THREAD

**Issue by kokojacket** [Deeptrain-Community/chatnio#137]
![image](https://github.com/Deeptrain-Community/chatnio/assets/74887370/77c9cff8-5953-496f-8d07-470e1f0fb7e9)

**Comment by kokojacket** [comment]
![Clip_2024-03-26_22-27-13](https://github.com/Deeptrain-Community/chatnio/assets/74887370/908e7773-6462-46fc-bd8a-001bd23d1bee)
复现了，官方网站。首个问题太长，导致会话命名长度过长

**Comment by zmh-program** [comment]
![image](https://github.com/Deeptrain-Community/chatnio/assets/112773885/ae71561f-0a76-4c35-a1b2-8d0baf07f4e1)
我看到了。等处理。

**Comment by zmh-program** [comment]
![image](https://github.com/Deeptrain-Community/chatnio/assets/112773885/27aabff1-b8bc-4f46-be09-fa569caddb9c)
