### ISSUE TITLE
模型列表点击未生效

### ISSUE THREAD

**Issue by kokojacket** [Deeptrain-Community/chatnio#139]
![image](https://github.com/Deeptrain-Community/chatnio/assets/74887370/9e47ee67-1328-4cdb-a3bb-1509f0dfc32c)
![image](https://github.com/Deeptrain-Community/chatnio/assets/74887370/38a21dba-8215-439b-a648-24ff0d6e7956)

**Comment by zmh-program** [comment]
无法复现

**Comment by kokojacket** [comment]
![recording](https://github.com/Deeptrain-Community/chatnio/assets/74887370/23feb9f2-5515-44ec-b6e0-de829021683b)
