### ISSUE TITLE
midjourney模型返回报错仍然消耗点数

### ISSUE THREAD

**Issue by chbkqx** [Deeptrain-Community/chatnio#14]
在使用midjourney
![Screenshot_2023-11-24-22-06-15-135_mark via](https://github.com/Deeptrain-Community/chatnio/assets/130931908/ea5f4bb9-6185-41e1-a657-0d189d22a9bb)
的过程中，出现如下报错：
```progress
100
```
```progress
100
```
```progress
100
```
error from midjourney: task failed: [Blocked] You have been blocked from accessing Midjourney. This happens on repeated or serious ToS violations.
和如下报错
error from midjourney: task failed: The resource is being rate limited.
在这两个报错情况中，chatnio都对我执行了0.5个点的扣费。
而一般情况下，没有给出图片，理应不执行扣费。在这个方面，希望能够进行一定程度的错误识别和不扣费机制。

**Comment by zmh-program** [comment]
midjourney被封号了，以及有错误识别和不扣费机制。这是因为 midjourney-proxy 项目返回的内容不是报错，而是正常请求，所以会正常扣费。我觉得你应该去 midjourney-proxy 提issue而不是这里
