### ISSUE TITLE
Support Hide Model Selector Option

### ISSUE THREAD

**Issue by xshadow0x** [Deeptrain-Community/chatnio#141]
I suggest create a customization option or set the main interface so that the message from ChatGPT does not stretch across the entire screen if the line is long, but is only displayed in a limited part of the screen (for example, in the middle of the screen) like on the official website

Also, make the text input field expand if there is a long prompt so that it is more convenient to work with, like on the official website. I also suggest moving the model selection somewhere else, perhaps below the input context line, and placing this selection in a different location, for example, before starting the dialogue or in a corner, because at the bottom it takes up a lot of screen space, which sometimes requires scrolling the page longer.

Additionally, you could make the context window shorter and center it slightly like on the official ChatGPT website. This will make it look much better.

These are just my suggestions on what could be done, you can decide for yourself. My job is to suggest :)

**Comment by zmh-program** [comment]
Thanks for the suggestion!
With long text, the text box doesn't take up the whole screen:
![image](https://github.com/Deeptrain-Community/chatnio/assets/112773885/ee414c8e-f9e3-463b-aa21-23300a4f81f0)

The model selection box does take up a lot of space, so I'm thinking of writing an option in the settings : "Whether to hide the model selection box below"
The default is not hidden, after hiding the subsequent selection can also be selected in the action box above the input box:
![image](https://github.com/Deeptrain-Community/chatnio/assets/112773885/83421733-0a15-4810-ba3f-8329d8552c69)
![image](https://github.com/Deeptrain-Community/chatnio/assets/112773885/3ec4a498-ea5a-4deb-9926-b3fdfcaa4166)
