### ISSUE TITLE
谁能帮讲讲chatnio的计费逻辑呢？

### ISSUE THREAD

**Issue by sslzhou948** [Deeptrain-Community/chatnio#145]
谁能帮讲讲chatnio的计费逻辑呢？看了手册的价目表没太看明白。。。比如 点数、1元=1美金(是倍率*7？)  由于我要接入中转站，那个站本身也有倍率，是中转倍率*nio倍率吗？

**Comment by zmh-program** [comment]
chatnio 没有倍率一说。
10 点数写死为 1 人民币。

**Comment by zmh-program** [comment]
![Screenshot_20240322_185734_edit_36309027835298.jpg](https://github.com/Deeptrain-Community/chatnio/assets/112773885/fab6507c-5aa2-4f75-9893-d54707e1b519)

可以通过设置 **计费规则** 中的 美元兑人民币设置 *USD:CNY* 汇率。
