### ISSUE TITLE
在MAC设备上的输入法回车导致异常发送

### ISSUE THREAD

**Issue by yangg** [Deeptrain-Community/chatnio#148]
设置里 Send Key 是 Enter 时， rt。

**Comment by zmh-program** [comment]
Windows 和 Ubuntu 都无法复现。

**Comment by yangg** [comment]
> Windows 和 Ubuntu 都无法复现。

现在用的 mac 的 Chrome，微信输入法

**Comment by zmh-program** [comment]
我没有 Mac 设备，此问题无法得到复现。

**Comment by zmh-program** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4322

我在此项目的issue中也找到了兴许类似的 point
