### ISSUE TITLE
再次出现了Dalle的图片缓存丢失问题

### ISSUE THREAD

**Issue by kokojacket** [Deeptrain-Community/chatnio#157]
![image](https://github.com/Deeptrain-Community/chatnio/assets/74887370/174011ac-bed3-4504-9914-218a7fc079ac)

**Comment by zmh-program** [comment]
![image](https://github.com/Deeptrain-Community/chatnio/assets/112773885/44f2dd14-1cf6-45eb-be03-be2d613cb381)
打开图片存储 配置好后端域名

**Comment by kokojacket** [comment]
![image](https://github.com/Deeptrain-Community/chatnio/assets/74887370/71944a89-4046-44d7-8c6a-8f23885fec39)
![image](https://github.com/Deeptrain-Community/chatnio/assets/74887370/f7ff9683-d307-4c67-8efd-f2d48c73eaf7)
已开启

**Comment by zmh-program** [comment]
是配置好 开启后请求的么
点你没显示图片的消息里的“编辑消息” 看看里面的内容

**Comment by kokojacket** [comment]
是的好早就配置好了。
![image](https://github.com/Deeptrain-Community/chatnio/assets/74887370/332de7c6-bb0e-4006-a5fb-fe87b062734e)

**Comment by zmh-program** [comment]
![image](https://github.com/Deeptrain-Community/chatnio/assets/112773885/50268fa8-7f01-4d21-835b-acca64278819)

**Comment by kokojacket** [comment]
重新设置后确实好了。不过之前确实也设置过后端域名和存储开启。目前没问题了
