### ISSUE TITLE
APP:// CORS问题

### ISSUE THREAD

**Issue by conql** [Deeptrain-Community/chatnio#158]
使用[OpenAI Node API库](https://www.npmjs.com/package/openai)请求时会导致CORS错误。
![image](https://github.com/Deeptrain-Community/chatnio/assets/49243542/bb22de0a-a71b-4aa2-909c-c096b7ce4ac1)

X-Stainless-.......的请求头是由OpenAI的官方库引入的
![image](https://github.com/Deeptrain-Community/chatnio/assets/49243542/4b2ce74a-8480-41f1-b31d-8475475c51f4)

**Comment by zmh-program** [comment]
自定义请求头一般是不会影响的，目测可能是app:// scheme的问题

**Comment by conql** [comment]
> 自定义请求头一般是不会影响的，目测可能是app:// scheme的问题

又测试了一下，好像不是


![image](https://github.com/Deeptrain-Community/chatnio/assets/49243542/504f4fc5-36aa-4106-a522-dcb14ba92de8)

复现代码：
await fetch("https://api.chatnio.net/v1/models",{
    method:"POST",
    headers:{
    }
}).then(t=>console.log("No Header",t.json()))

await fetch("https://api.chatnio.net/v1/models",{
    method:"POST",
    headers:{
        "X-Stainless-Lang":"js"
    }
}).then(t=>console.log("Has Header",t.json()))

**Comment by zmh-program** [comment]
这是你的app的问题吧

**Comment by conql** [comment]
![image](https://github.com/Deeptrain-Community/chatnio/assets/49243542/fdbd798b-42c3-4a0a-b214-df6732a6d96c)

**Comment by conql** [comment]
在https://chatnio.net上跑也一样

**Comment by zmh-program** [comment]
浏览器？

**Comment by conql** [comment]
是的

**Comment by zmh-program** [comment]
OK 复现到了 等我处理完#77来处理
