### ISSUE TITLE
可以用本地模型吗？比如ollama

### ISSUE THREAD

**Issue by 877075166** [Deeptrain-Community/chatnio#159]

**Comment by zmh-program** [comment]
Chat Nio 支持 LocalAI 等本地模型聚合。

Ollama 支持 OpenAI 格式，可以通过 OpenAI 格式接入：
https://ollama.com/blog/openai-compatibility

接入点填 `http://[ip]:[port]` 即可

**Comment by zmh-program** [comment]
也可使用 `LocalAI`, 支持 LLAMA/RWKV/SDXL 等模型
