### ISSUE TITLE
api跨域问题

### ISSUE THREAD

**Issue by ElmTran** [Deeptrain-Community/chatnio#161]
- 问题描述：
  在长时间未使用，重新登录的时候在deeptrain跳转回chatnio的时候失败。控制台报错跨域问题。后面报504，网关错误。该问题已重复出现多次，稳定复现。

- 我的尝试：
  1. 切换代理节点
  2. 关闭代理
  3. 更换电脑，个人电脑未出现这种情况。
  4. 使用隐私模式

- 补充截图：
![image](https://github.com/Deeptrain-Community/chatnio/assets/34189785/f5246639-4da4-4955-bda8-649b2cabe2e0)

**Comment by zmh-program** [comment]
这是官网被打了，报错 504 Bad Gateway， 不是软件问题，请前往用户群咨询
