### ISSUE TITLE
[Option] 用户渲染 markdown 选项

### ISSUE THREAD

**Issue by NOname-awa** [Deeptrain-Community/chatnio#162]
我认为可以在设置里添加一个选项用于控制是否开启用户渲染 markdown，使用 “```” 发送的代码具有等宽的字体，关闭 markdown 渲染后反而会导致用户读自己发送的代码不好读，所以我认为可以在设置中添加一个选项用于打开或者关闭渲染 markdown

**Comment by zmh-program** [comment]
related #141
