### ISSUE TITLE
使用智普模型预设报错

### ISSUE THREAD

**Issue by xia01eng** [Deeptrain-Community/chatnio#163]
![image](https://github.com/Deeptrain-Community/chatnio/assets/31816340/ef068f13-7927-46f2-a1cf-89008f7b3942)
是不是chatnio的预设对智普AI的兼容性没做好，预设提示词会报错，有没有人遇到过的，求教

**Comment by zmh-program** [comment]
请提供 chatnio 版本

**Comment by zmh-program** [comment]
温馨提示：版本在偏好设置里

**Comment by zmh-program** [comment]
没看见有回复哈，我说一下，关联 #147 ，之前已经是有这个问题的，从这条 commit 以后，
https://github.com/Deeptrain-Community/chatnio/commit/5ddfbbc2955ff1f1d0a4dcdb693711e28c213fca
已经修复此问题，请更新 chatnio 版本。
我无法复现此问题：
![image](https://github.com/Deeptrain-Community/chatnio/assets/112773885/66f5d790-23d5-458d-af81-3e36450e0aa8)

如果最新版仍有此问题，请在 reopen 此 issue 或者在下方留言。
