### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by McKinleyLu** [Deeptrain-Community/chatnio#165]
Why not add support for the suno model? 

In fact, there are already many suno API intermediaries, you can set up billing per use. 

If you could add it, that would be great. 

Thank you!
![image](https://github.com/Deeptrain-Community/chatnio/assets/45777553/119d209a-a99d-4590-8d5e-b5135487fcd4)

**Comment by zmh-program** [comment]
https://github.com/songquanpeng/one-api/issues/1243

没 api，现在都是逆向的suno 转 openai，参考oneapi这个issue, chatnio不接逆向, 请通过逆向接chatnio的openai格式，请不要让suno起诉我 :(
No api, now it's all reverse suno to openai, refer to oneapi this issue, chatnio doesn't take reverse, please take chatnio's openai format through reverse, please don't let suno sue me :(
