### ISSUE TITLE
前端单独打包接口地址困扰

### ISSUE THREAD

**Issue by xia01eng** [Deeptrain-Community/chatnio#166]
您好，我希望能够把前端代码单独编译打包到nginx上，但是请求地址一直500报错，我注意到app文件夹中有vite.config.js，这里面配置了代理转发
`  server: {
    proxy: {
      "/api": {
        target: "http://localhost:8094",
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/api/, ""),
        ws: true,
      },
      "/v1": {
        target: "http://localhost:8094",
        changeOrigin: true,
      }
    }
  }`
我尝试修改了target为线上通过容器安装且能正常请求的后端地址，可是一直不生效，浏览器中的请求header仍然指向localhost:5173(我本地项目前端运行的地址)，请教该如何修改。

**Comment by zmh-program** [comment]
vite里面是开发环境的mock server

**Comment by zmh-program** [comment]
![Screenshot_20240409_142311.jpg](https://github.com/Deeptrain-Community/chatnio/assets/112773885/00e16b4a-42a3-47c7-a41a-a618a73e5266)

**Comment by zmh-program** [comment]
![Screenshot_20240409_142311_edit_100518093479526.jpg](https://github.com/Deeptrain-Community/chatnio/assets/112773885/d239add1-a260-4735-b4c8-6f0a933ed462)

文档都有

**Comment by xia01eng** [comment]
![image](https://github.com/Deeptrain-Community/chatnio/assets/31816340/d2795d7b-7fd9-4a6a-bbdd-b7e48e2afc51)
是这个变量吗，我修改过我的线上地址，但是登录请求还是localhost
![image](https://github.com/Deeptrain-Community/chatnio/assets/31816340/983f43d5-f48e-41b2-ab73-959b085f6340)

**Comment by zmh-program** [comment]
.env

**Comment by xia01eng** [comment]
![image](https://github.com/Deeptrain-Community/chatnio/assets/31816340/f82bab73-56c8-4aa2-aebf-9104234f256b)
登录跳官网了 = =

**Comment by zmh-program** [comment]
你为啥要用deeptrain模式。。。

**Comment by xia01eng** [comment]
VITE_USE_DEEPTRAIN=false
这个是不是就不通deeptrain模式啊

**Comment by zmh-program** [comment]
是 或者直接删了

**Comment by zmh-program** [comment]
.env.deeptrain 模式就是官网， 我意思是让你在打包的时候配置环境变量 ，或者新建一个 .env 文件配置环境，没让你复制 .env.deeptrain ...

**Comment by xia01eng** [comment]
搞定了！谢谢哈哈哈

**Comment by zmh-program** [comment]
OK
