### ISSUE TITLE
需要支持 gemini 1.5 api

### ISSUE THREAD

**Issue by luowei729** [Deeptrain-Community/chatnio#169]
需要支持 gemini 1.5 api

**Comment by zmh-program** [comment]
自定义模型即可

**Comment by zmh-program** [comment]
内置价格模板和模型模板商业版已支持，由 @Sh1n3zZ 下放commit至开源版

**Comment by luowei729** [comment]
> 自定义模型即可

报错怎么处理
gemini error: models/gemini-1.5-pro is not found for API version v1beta, or is not supported for GenerateContent. Call ListModels to see the list of available models and their supported methods. (code: 404, status: NOT_FOUND)
