### ISSUE TITLE
How to install this project on a debian or rockylinux server, is there a detailed procedure?

### ISSUE THREAD

**Issue by ikexue** [Deeptrain-Community/chatnio#17]
How to deploy a server like debian or rockylinux, is there a detailed procedure?

**Comment by zmh-program** [comment]
Deploying it now can be a bit tricky, you need to deploy a Deeptrain Unified Account Management and get the WeChat and Alipay Enterprise Payment APIs

**Comment by zmh-program** [comment]
This is [deeptrain](https://github.com/Deeptrain-Community/Deeptrain)

**Comment by zmh-program** [comment]
We are planning to implement all in one and deploy it in an easy way, such as supporting *docker-compose* installations etc.

**Comment by ikexue** [comment]
thank you very much

**Comment by zmh-program** [comment]
we support all in one now.
