### ISSUE TITLE
数学公式不渲染是什么问题呢

### ISSUE THREAD

**Issue by ersaijun** [Deeptrain-Community/chatnio#170]
遇到数学公式无法正常显示，请问是什么原因呢 
![image](https://github.com/Deeptrain-Community/chatnio/assets/16569525/74b9cc03-4162-41c6-83ee-db478e6230cf)

**Comment by zmh-program** [comment]
这是 gpt 的问题，公式应该用 $$ [公式] $$ 包裹

**Comment by zmh-program** [comment]
同 #19
