### ISSUE TITLE
SMTP发送邮件失败

### ISSUE THREAD

**Issue by fighter2011** [Deeptrain-Community/chatnio#172]
自定义域名邮箱，走resend服务的smtp服务发送失败，但是使用go的net/smtp包发送没有问题

**Comment by zmh-program** [comment]
报错信息 smtp配置 日志

**Comment by fighter2011** [comment]
报username invalid
![Uploading iShot_2024-04-18_14.32.29.png…]()

**Comment by zmh-program** [comment]
比如你用 postmaster@deeptrain.net 邮箱发件

用户名为 postmaster
发件人为 postmaster@deeptrain.net
