### ISSUE TITLE
问一下这个可以设置默认开启亮色模式吗？

### ISSUE THREAD

**Issue by kbc1118** [Deeptrain-Community/chatnio#173]
不太喜欢默认的暗色调 ，可以开启默认亮色吗？

**Comment by zmh-program** [comment]
https://github.com/Deeptrain-Community/chatnio/blob/72af27b26a44f1c754cb4ce98988e3464f741b3e/app/src/components/ThemeProvider.tsx#L8

改成 `light`

**Comment by kbc1118** [comment]
三克油
