### ISSUE TITLE
SMTP服务改进

### ISSUE THREAD

**Issue by SHLE1** [Deeptrain-Community/chatnio#174]
- 在使用第三方smtp服务商时，“**用户名**”这一栏经常会要求填写自己的注册账号比如“**xxx@gmail.com**“来进行验证，但是chatnio用户名一栏似乎不支持在“*用户名*”一栏出现“**@**”符号，会提示“**SMTP 发件参数未正确配置，已禁用邮箱验证**”。
- 希望能去掉这一限制以更好的支持第三方smtp服务。（个人使用brevo，确认配置正确，在其他项目可以发送邮件）
- 
<img width="970" alt="image" src="https://github.com/Deeptrain-Community/chatnio/assets/101321085/a4f82bae-a05b-4398-a6ef-8d68206e328a">

**Comment by zmh-program** [comment]
用户名要去掉@后面的 只需要填smtp的username
发件人才要加@后面的

**Comment by zmh-program** [comment]
比如你用 [postmaster@deeptrain.net](mailto:postmaster@deeptrain.net) 邮箱发件

用户名为 postmaster
发件人为 [postmaster@deeptrain.net](mailto:postmaster@deeptrain.net)

**Comment by KyrieNO1** [comment]
- 问题就是username是service@mydomain.com，含有@就提示“**SMTP 发件参数未正确配置，已禁用邮箱验证**“
- 例如我用的brave，sender为service@mydomain.com，在用户名处填service是无法通过brevo的验证的，会弹“**请求失败
sent mail failed: 535 5.7.8 Authentication failed**“
- 这是smtp的设置，在[smtpserver](https://smtpserver.com/cn/smtptest)测试时将“login“填入”用户名“框才可以发送成功，而在chatnio并不允许将“login“填入“用户名“，所以无法通过认证
- 因为登陆邮箱和发件邮箱并不同，所以区分了用户名和发件人。在one-api的smtp设置中，也区分了smtp账户和smtp发送者邮箱。
<img width="1342" alt="image" src="https://github.com/Deeptrain-Community/chatnio/assets/101321085/b9d07034-98a2-4f4f-bf9f-fa894bff724c">

**Comment by zmh-program** [comment]
smtp server 和 port 填的没问题，用户名应该填你的 brevo 用户名，发件人填你的 login 

https://github.com/Deeptrain-Community/chatnio/blob/main/utils/smtp.go#L33-L56

**Comment by zmh-program** [comment]
正常 SMTP 发件 用户名填入@后缀是无法工作的

**Comment by KyrieNO1** [comment]
- 您说的这样确实可以，但是这样的收件人端显示发件人是代发而不是xxx@mydomain.com。
- 可否像[独角数卡](https://github.com/assimon/dujiaoka/blob/b0f59699a31895fd2769327332d52a9b4c0d916c/app/Jobs/MailSend.php)一样，添加更多自定义配置来实现？
- 感谢您的耐心回复和指导
<img width="893" alt="63CBDA82-2B95-4266-9575-FFD483E8CDCE" src="https://github.com/Deeptrain-Community/chatnio/assets/101321085/370b3e6b-9a48-48f3-8ac3-9167f8f45c07">

**Comment by zmh-program** [comment]
我刚刚注册了一下 brevo，发现无法正常工作，即使通过去除用户名的@限制后`mail.v2`库也无法工作。 
看样子和其他 SMTP 服务有区别，等我有空研究一下，看看如何修复。

**Comment by emengweb** [comment]
> 用户名要去掉@后面的 只需要填smtp的username 发件人才要加@后面的

mxroute的邮局，发件用户名使用的是邮箱地址，不过试了465\25\587端口，均报错无法正常发送测试邮件

**Comment by zmh-program** [comment]
用户名去掉@就好了？

**Comment by zmh-program** [comment]
> > 用户名要去掉@后面的 只需要填smtp的username 发件人才要加@后面的
> 
> 测试使用mxroute的邮局（发件用户名使用的是邮箱地址）尝试使用 465\25\587 端口，均报错无法正常发送测试邮件

用户名去掉@就好了？

**Comment by emengweb** [comment]
mxroute的邮局的发件用户名是邮箱地址，使用这套配置在其他项目中可以正常发信，但在ChatNio就报错了

Minghan Zhang ***@***.***> 于2024年5月9日周四 09:35写道：

**Comment by zmh-program** [comment]
推荐使用腾讯云 SES / QQ / Gmail 等 SMTP 服务商

**Comment by Sh1n3zZ** [comment]
Greetings For @SHLE1 @emengweb ,

该问题已修复，同时依需要增加了部分功能。具体分析和其他相关信息可见我刚刚提交的 pr #213 。
目前该 pr 正在等待 merge ，您可以选择前往 https://github.com/Deeptrain-Community/chatnio/tree/Rakuyou_Dev 分支拉取最新代码或等待主分支合并。

Best Regards,
Junhai Deng

**Comment by whitewatercn** [comment]
阿里云也报错了，用户名没填艾特，发信地址正确，smtp地址正确，在其他地方用完全没问题
<img width="766" alt="image" src="https://github.com/user-attachments/assets/d44a1b24-cc9b-4800-8a8b-1f21f6e2f65c" />

<img width="249" alt="image" src="https://github.com/user-attachments/assets/40cd6738-dec6-4557-a53d-3530fdcbe918" />

<img width="1027" alt="image" src="https://github.com/user-attachments/assets/05f2dc59-733b-436d-abf9-3c81e15813e2" />
