### ISSUE TITLE
[Feat] 支持侧边栏：在边栏直接选择预设 Tab，一键创建带预设的新对话

### ISSUE THREAD

**Issue by draplater** [Deeptrain-Community/chatnio#176]
目前选择预设需要：新建对话->点击选择预设按钮->选择预设，步骤比较繁琐，容易忘记
可以模仿ChatGPT，支持在边栏直接选择预设（类似GPTs），一键创建带预设的新对话

**Comment by zmh-program** [comment]
比如如何设计？

**Comment by eddsi** [comment]
@zmh-program 我最近也在想如何设计这个功能，有点思路，交流一下？

**Comment by zmh-program** [comment]
im here to listen

**Comment by eddsi** [comment]
按下预设按钮，用一个组件替换ChatWrapper，该组件展示多个矩形框，每一个矩形框是一个mask，矩形框内可以放图片、介绍等。我在b站给你私信了，你看下

**Comment by zmh-program** [comment]
@eddsi 不好意思，我不怎么看 b 站，而且如果就谈论这个 issue 而言在这里其实更方便，如果是有什么需要的话再说。

比如类似于这样吗，这是我们目前chatnio商业版的dev preview:
![e54e394567970644c0fe5b8bf6959761_720](https://github.com/Deeptrain-Community/chatnio/assets/112773885/c3b8d378-008a-480f-98cc-83edaae6cdbe)

**Comment by eddsi** [comment]
是的，就是图中那样，我正在开发这个功能。主要是想问一下怎么成为Contributor，还有你的个人主页，方便留个联系方式吗。

**Comment by zmh-program** [comment]
wechat同名

**Comment by draplater** [comment]
@eddsi 可以将讨论内容和设计方案在此公开不，便于共同开发

**Comment by eddsi** [comment]
@draplater 过几天我准备更新代码，增加上述功能，在这个仓库里，https://github.com/BoomTeam2018/chatboom

**Comment by zmh-program** [comment]
新 UI 已经上线 chatnio 商业版和官网 此 Issue 将被关闭，*开源版不进行新 UI 更新*。

![Image_1717344023145.png](https://github.com/Deeptrain-Community/chatnio/assets/112773885/07ffdfb8-c1b7-4f22-8a3a-b14e0a1ff190)

> 更多新 UI 请前往 [chatnio 官网](https://chatnio.net)
