### ISSUE TITLE
编译出来的mac app 报网络错误

### ISSUE THREAD

**Issue by wlevene** [Deeptrain-Community/chatnio#179]
服务地址改到自己搭建的服务器，通过docker安装的
网页版本是正常工作的
地址弹出看过了，是正确的

<img width="729" alt="image" src="https://github.com/Deeptrain-Community/chatnio/assets/1000877/b41400e5-37c3-418b-9cf7-ecef248b6cc7">

**Comment by zmh-program** [comment]
Tauri 打包的应用 F12 应该是可以看到控制台的 提供一下日志

**Comment by wlevene** [comment]
dev 模式报错如下：
![image](https://github.com/Deeptrain-Community/chatnio/assets/1000877/b94c6283-2da6-4337-b30d-9f124cb81298)
![image](https://github.com/Deeptrain-Community/chatnio/assets/1000877/ee10492d-c820-4c34-90c2-2e4e23693245)

release 报的是最开始的上面提到的内容，两个错误还不一样

release模式下的包 是不是打不开这个调试面板呀，试了 F12和其它方式，并没能打开控制台

**Comment by zmh-program** [comment]
看url

**Comment by wlevene** [comment]
<img width="645" alt="image" src="https://github.com/Deeptrain-Community/chatnio/assets/1000877/e2217953-bb17-4f1f-9e80-2e5d522c3541">

**Comment by zmh-program** [comment]
要加/api

**Comment by wlevene** [comment]
debug可以了，  感谢。 release还是不行  

cargo tauri dev 可以工作
cargo tauri build 还是同样的报错
![image](https://github.com/Deeptrain-Community/chatnio/assets/1000877/a5d60bb0-22f4-4491-a6d7-ec0363cb8979)
![image](https://github.com/Deeptrain-Community/chatnio/assets/1000877/4032a304-1ac4-4b65-8cbd-28bc1cd46e1e)

**Comment by zmh-program** [comment]
环境变量，配置有没有更改, dev 是否设置为 true

https://github.com/Deeptrain-Community/chatnio/blob/b87919114c211f7ba691372450c5e645f22a929a/app/src/conf/env.ts#L42-L71

**Comment by zmh-program** [comment]
还有，非商业版，需要把 --mode deeptrain 删掉
https://github.com/Deeptrain-Community/chatnio/blob/main/app/src-tauri/tauri.conf.json#L4

**Comment by wlevene** [comment]
![image](https://github.com/Deeptrain-Community/chatnio/assets/1000877/79a7a957-874a-44dc-8faa-615e2d492569)
![image](https://github.com/Deeptrain-Community/chatnio/assets/1000877/9ec14deb-3ff5-4ebf-9cb6-3d78b55c3b6d)


还是一样报网络错

**Comment by zmh-program** [comment]
提供你的参数配置和环境变量

**Comment by zmh-program** [comment]
> ![image](https://github.com/Deeptrain-Community/chatnio/assets/1000877/79a7a957-874a-44dc-8faa-615e2d492569)
> ![image](https://github.com/Deeptrain-Community/chatnio/assets/1000877/9ec14deb-3ff5-4ebf-9cb6-3d78b55c3b6d)
> 
> 
> 还是一样报网络错

没让你这么改...

**Comment by wlevene** [comment]
![image](https://github.com/Deeptrain-Community/chatnio/assets/1000877/2c600332-b58c-4b5d-86fa-fc70c05e3e25)
![image](https://github.com/Deeptrain-Community/chatnio/assets/1000877/0e5b587f-ff47-42af-8696-6a69701ad530)

**Comment by zmh-program** [comment]
.env
加上/api

vite的.env的优先级大于config

**Comment by wlevene** [comment]
![image](https://github.com/Deeptrain-Community/chatnio/assets/1000877/b05f32b6-4bfe-4c1e-aca4-d65f7e53560b)
加上了 /api

**Comment by zmh-program** [comment]
server error是谁加的，前端提供具体的服务端返回的response发过来

**Comment by wlevene** [comment]
![image](https://github.com/Deeptrain-Community/chatnio/assets/1000877/29191879-1b96-42c9-a690-3ac2cf50da67)
前端提供具体的服务端返回的response在 release模式下不知道怎么看 。。。    release打不开控制台吧

**Comment by zmh-program** [comment]
改一下toast的报错信息

**Comment by wlevene** [comment]
要改成啥 : ( 前端 新手，尴尬

**Comment by zmh-program** [comment]
浏览器能复现吗，如果是浏览器能复现到相同问题的话你可以看一下浏览器的返回。

一般如果是chatnio的bug的话，tauri和正常浏览器都是相同的报错

**Comment by wlevene** [comment]
浏览器                     没问题
cargo tauri dev      没问题
cargo tauri build    报错

**Comment by zmh-program** [comment]
那怪了，一样的配置 应该是所有地方都有问题才对，我怀疑可能是 tauri 自身哪部分的配置有问题 
但是我 Windows / Ubuntu 都无法复现此问题

**Comment by wlevene** [comment]
感谢耐心回复，我再研究下，应该是我环境那里有问题

**Comment by zmh-program** [comment]
我没有 Mac 设备，此问题转接 @XiaomaiTX

**Comment by XiaomaiTX** [comment]
Mark，于工作日查看，休假ing
QWQ
