### ISSUE TITLE
无法获取 api key

### ISSUE THREAD

**Issue by wenwen12345** [Deeptrain-Community/chatnio#18]
使用google登录，api设置为空，无法复制
![image](https://github.com/Deeptrain-Community/chatnio/assets/76639973/5c4e965b-57d8-4eba-950b-e6b82ff703f5)

**Comment by zmh-program** [comment]
正常现象，第一次登录之后，刷新页面才有apikey，防止滥用的

**Comment by wenwen12345** [comment]
谢谢
