### ISSUE TITLE
[Bug] 在未请求成功阶段无法暂停问题

### ISSUE THREAD

**Issue by dqzboy** [Deeptrain-Community/chatnio#181]
在页面点击暂停回答没有任何反应，程序日志显示其实已经超时了，但是还是一直在转圈还不能暂停，如图
![PixPin_2024-05-05_12-27-01](https://github.com/Deeptrain-Community/chatnio/assets/42825450/da34bce1-c92f-424f-b50f-8e4f5df3e4ac)

**Comment by zmh-program** [comment]
这是因为 manager/chat 实现方法暂停其实是在流式响应的中途通过同步阻塞实现的，所以在请求发起之前会一直阻塞，不会处理stop signal，此时暂停是有问题的，后期我打算将其独立于一个goroutine中以快速暂停响应。

**Comment by dqzboy** [comment]
强👍

**Comment by zmh-program** [comment]
feat: better stop signal 商业版已率先修复，Waiting for @Sh1n3zZ 下放开源版
> todo: https://github.com/Deeptrain-Community/chatnio-pro/commit/bdab26f989b10322ba2a74392e52760634c0e674

**Comment by Sh1n3zZ** [comment]
Hi,

Done.

Junhai Deng
