### ISSUE TITLE
如何对接ollama本地模型

### ISSUE THREAD

**Issue by hfoi589** [Deeptrain-Community/chatnio#184]
宣传页中提到可以对接localAI，但是模型页面中的类型，没有localai的选项。并且目前密钥是必输的，localai有的不需要密钥

**Comment by AnnaStreeter** [comment]
issue #159 有人提到过

既然没有密钥，那就随便填一个就行了，ollama我密钥填的`null`可用

**Comment by hfoi589** [comment]
> issue #159 有人提到过
> 
> 既然没有密钥，那就随便填一个就行了，ollama我密钥填的`null`可用

我发现问题了，是模型的名称搞错了。。。。比如我跑的是qwen:7b，那我渠道里面的模型就只能叫qwen:7b
