### ISSUE TITLE
[Erro] 宝塔反代绑定域名后出现1006错误

### ISSUE THREAD

**Issue by taurusduan** [Deeptrain-Community/chatnio#186]
![image](https://github.com/Deeptrain-Community/chatnio/assets/30854760/a5535892-0616-4629-8ac4-ad5e7478acf3)
使用ip一切正常，但是使用域名就错误。

docker部署的。求救！求救！求救！

**Comment by dqzboy** [comment]
如果使用的是nginx，可通过下面的方式实现支持wss
- nginx proxy添加参数
```bash
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $connection_upgrade;
```
- http块添加参数
```bash
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
```

**Comment by taurusduan** [comment]
> 如果使用的是nginx，可通过下面的方式实现支持wss
> 
> * nginx proxy添加参数
> 
> ```shell
> proxy_set_header Upgrade $http_upgrade;
> proxy_set_header Connection $connection_upgrade;
> ```
> 
> * http块添加参数
> 
> ```shell
> map $http_upgrade $connection_upgrade {
>     default upgrade;
>     ''      close;
> }
> ```

大哥咨询一下，我是新手，使用的是宝塔NGINX反代的容器，这个要怎么修改啊，谢谢啊大哥。

**Comment by AnnaStreeter** [comment]
网上好多教程可以去看看，以及chatnio项目根目录下有个nginx.conf可以借鉴一下。
