### ISSUE TITLE
【求助】api无法使用，不知道是不是自己搞错了。

### ISSUE THREAD

**Issue by taurusduan** [Deeptrain-Community/chatnio#188]
![image](https://github.com/Deeptrain-Community/chatnio/assets/30854760/1e1aadaa-d378-496c-8a63-867e6bb0bad4)
复制key
![image](https://github.com/Deeptrain-Community/chatnio/assets/30854760/80f40f3b-6386-45c9-b85a-96788b562c50)

检查之后没有反应，也无法获取模型列表
不知道是不是自己什么地方没有弄，求助！求助！求助！

**Comment by AnnaStreeter** [comment]
自己用浏览器访问一下 https://xxx/v1/models 呗

**Comment by taurusduan** [comment]
> 自己用浏览器访问一下 https://xxx/v1/models 呗

大佬看了，什么都没有...
![image](https://github.com/Deeptrain-Community/chatnio/assets/30854760/9fdf1b52-70fe-4742-8f40-03ab15f12876)
是不是还要设置什么地方啊

**Comment by AnnaStreeter** [comment]
用curl测

**Comment by taurusduan** [comment]
> models

![image](https://github.com/Deeptrain-Community/chatnio/assets/30854760/c675bfc4-8ca8-422b-9b37-bd8f205d1eb5)
改成这样可以获取模型了，但是无法联通

**Comment by AnnaStreeter** [comment]
你先可以翻译一下，这个意思是这个模型的价格没有设定/渠道里没有这个模型。

**Comment by taurusduan** [comment]
> 你先可以翻译一下，这个意思是这个模型的价格没有设定/渠道里没有这个模型。

大佬是不是说这个调用和订阅次数是分开计算的。

**Comment by taurusduan** [comment]
> 你先可以翻译一下，这个意思是这个模型的价格没有设定/渠道里没有这个模型。

大佬搞定了，原来就是订阅的问题，我设置的是订阅次数，但是这个调用不计入订阅，只能按照次数来计算，是没有积分了，所以失败。谢谢大佬的指导。

**Comment by AnnaStreeter** [comment]
> > 你先可以翻译一下，这个意思是这个模型的价格没有设定/渠道里没有这个模型。
> 
> 大佬搞定了，原来就是订阅的问题，我设置的是订阅次数，但是这个调用不计入订阅，只能按照次数来计算，是没有积分了，所以失败。谢谢大佬的指导。

奥，订阅配额默认是不支持api调用中使用的，我看系统设置里有的： 站点设置->订阅配额涵盖 API，你可以打开就可以 API 扣费的时候优先使用订阅配额扣费了。

我感觉这个选项设计蛮合理的，我觉得这么设计的目的是 怕以token计费的模型（比如gpt-4-turbo万一api一下子128k上下文全占满了）被盗刷就亏了不少，默认不让订阅配额的次数支持api是合理的。然后也可以通过开启此选项支持配额。

**Comment by taurusduan** [comment]
> > > 你先可以翻译一下，这个意思是这个模型的价格没有设定/渠道里没有这个模型。
> > 
> > 
> > 大佬搞定了，原来就是订阅的问题，我设置的是订阅次数，但是这个调用不计入订阅，只能按照次数来计算，是没有积分了，所以失败。谢谢大佬的指导。
> 
> 奥，订阅配额默认是不支持api调用中使用的，我看系统设置里有的： 站点设置->订阅配额涵盖 API，你可以打开就可以 API 扣费的时候优先使用订阅配额扣费了。
> 
> 我感觉这个选项设计蛮合理的，我觉得这么设计的目的是 怕以token计费的模型（比如gpt-4-turbo万一api一下子128k上下文全占满了）被盗刷就亏了不少，默认不让订阅配额的次数支持api是合理的。然后也可以通过开启此选项支持配额。

打开了，应该不行吧，我再试试看啊

**Comment by AnnaStreeter** [comment]
什么不行

**Comment by AnnaStreeter** [comment]
什么不行

**Comment by taurusduan** [comment]
> 什么不行

订阅功能应该有问题，大佬你看看是不是什么地方出错了，我这边给你展示一下：
![image](https://github.com/Deeptrain-Community/chatnio/assets/30854760/017363df-c983-490b-a2eb-bbb74e596bc5)
我对话了两次。
这是账号里的订阅统计
![image](https://github.com/Deeptrain-Community/chatnio/assets/30854760/d4ea605c-257d-44bc-a418-485a0e64d683)
这是积分的统计
![image](https://github.com/Deeptrain-Community/chatnio/assets/30854760/2bd5bbe3-ffd4-4ef7-af5c-f4c241b5e633)
如果把订阅和订阅配额涵盖 API关闭就可以正常统计了。这个不知道是不是bug
![image](https://github.com/Deeptrain-Community/chatnio/assets/30854760/c968e3d7-a5b7-43b3-ae6c-9dda8492602f)

**Comment by AnnaStreeter** [comment]
刷新一下浏览器，就好了，我是开订阅配额支持api的，没发现有什么问题

**Comment by taurusduan** [comment]
> 刷新一下浏览器，就好了，我是开订阅配额支持api的，没发现有什么问题

啊，我这边直接就重新用了一个浏览器，我这边对话不会消耗。

**Comment by taurusduan** [comment]
> 刷新一下浏览器，就好了，我是开订阅配额支持api的，没发现有什么问题

大佬你这边是调用api吗？我这边如果开了调用api真的不会消耗积分或者订阅次数

**Comment by AnnaStreeter** [comment]
![Screenshot_20240510_141821_edit_214382200069085](https://github.com/Deeptrain-Community/chatnio/assets/148262462/708a76e9-da84-443c-987b-02a12eb5434d)
![Screenshot_20240510_141751_edit_214389954600348](https://github.com/Deeptrain-Community/chatnio/assets/148262462/162f4c0e-8017-46fa-ae37-7b5506cd599d)

刚刚又测了一遍，正常，用python调用openai api

**Comment by taurusduan** [comment]
> ![Screenshot_20240510_141821_edit_214382200069085](https://private-user-images.githubusercontent.com/148262462/329479064-708a76e9-da84-443c-987b-02a12eb5434d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjIzNzYsIm5iZiI6MTcxNTMyMjA3NiwicGF0aCI6Ii8xNDgyNjI0NjIvMzI5NDc5MDY0LTcwOGE3NmU5LWRhODQtNDQzYy05ODdiLTAyYTEyZWI1NDM0ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQwNjIxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDU4YjA2YTIzNDdmNTA5MmE3ZmRkMGI3Y2IwMTAwZWFlMGQ0ZDhiNGI5MjBjY2I5NWM4OGE0NWFiZWZiOTFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NWmOH5z_25N8MYwINSwyZj1oaK_Br2jv7DQCnjnHfUA) ![Screenshot_20240510_141751_edit_214389954600348](https://private-user-images.githubusercontent.com/148262462/329479094-162f4c0e-8017-46fa-ae37-7b5506cd599d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjIzNzYsIm5iZiI6MTcxNTMyMjA3NiwicGF0aCI6Ii8xNDgyNjI0NjIvMzI5NDc5MDk0LTE2MmY0YzBlLTgwMTctNDZmYS1hZTM3LTdiNTUwNmNkNTk5ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQwNjIxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWZiZTYwNjFiZTNmZGM2ZmIzZDhlMWE4MjRjNGNkMjU2ZTVjMWM4MjI4NzU0ZWVkNGEyZTMzYWQ1NWEyMDM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XEVOjrLgZjqKGdHUUdDorpx2z2AJYVKj0HJidtAZi_U)
> 
> 刚刚又测了一遍，正常，用python调用openai api

这个就见鬼了，我这边客户端调用，不会消耗。。。

**Comment by AnnaStreeter** [comment]
复现不到

**Comment by taurusduan** [comment]
> > ![Screenshot_20240510_141821_edit_214382200069085](https://private-user-images.githubusercontent.com/148262462/329479064-708a76e9-da84-443c-987b-02a12eb5434d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjIzNzYsIm5iZiI6MTcxNTMyMjA3NiwicGF0aCI6Ii8xNDgyNjI0NjIvMzI5NDc5MDY0LTcwOGE3NmU5LWRhODQtNDQzYy05ODdiLTAyYTEyZWI1NDM0ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQwNjIxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDU4YjA2YTIzNDdmNTA5MmE3ZmRkMGI3Y2IwMTAwZWFlMGQ0ZDhiNGI5MjBjY2I5NWM4OGE0NWFiZWZiOTFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NWmOH5z_25N8MYwINSwyZj1oaK_Br2jv7DQCnjnHfUA) ![Screenshot_20240510_141751_edit_214389954600348](https://private-user-images.githubusercontent.com/148262462/329479094-162f4c0e-8017-46fa-ae37-7b5506cd599d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjIzNzYsIm5iZiI6MTcxNTMyMjA3NiwicGF0aCI6Ii8xNDgyNjI0NjIvMzI5NDc5MDk0LTE2MmY0YzBlLTgwMTctNDZmYS1hZTM3LTdiNTUwNmNkNTk5ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQwNjIxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWZiZTYwNjFiZTNmZGM2ZmIzZDhlMWE4MjRjNGNkMjU2ZTVjMWM4MjI4NzU0ZWVkNGEyZTMzYWQ1NWEyMDM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XEVOjrLgZjqKGdHUUdDorpx2z2AJYVKj0HJidtAZi_U)
> > 刚刚又测了一遍，正常，用python调用openai api
> 
> 这个就见鬼了，我这边客户端调用，不会消耗。。。

大佬咨询一下关于联网的问题，我按照说明自己搭建了DuckDuckGo API，绑定了域名，但是联网似乎用不了。
![image](https://github.com/Deeptrain-Community/chatnio/assets/30854760/6ab772df-3640-4e2c-9fd6-381d88165510)
配置
![image](https://github.com/Deeptrain-Community/chatnio/assets/30854760/ea8f37fa-5af4-40f7-a8e5-eaa79daed8dc)
不知道是不是配置错了

**Comment by AnnaStreeter** [comment]
文档里不是有说吗😂

**Comment by taurusduan** [comment]
> 文档里不是有说吗😂

找到问题了，不知道为什么我这边要对话几次之后，才会调用搜索

**Comment by AnnaStreeter** [comment]
开启联网搜索之后每一条消息都会请求
