### ISSUE TITLE
在部分设备和情况下markdown与latex数学公式解析错误

### ISSUE THREAD

**Issue by chbkqx** [Deeptrain-Community/chatnio#19]
先报一下设备，redmi9a，via浏览器。
![Screenshot_2023-12-04-23-20-28-170_mark via](https://github.com/Deeptrain-Community/chatnio/assets/130931908/633e1b6a-3072-4e4a-9515-0a607fbbed8d)
![Screenshot_2023-12-04-23-22-42-188_mark via](https://github.com/Deeptrain-Community/chatnio/assets/130931908/9e14443c-7c12-4fb6-ac7b-4e5325ac7a9a)
在此处，数学公式和markdown没有被正确的解析，直接以纯文本形式展示，包括回答中的文字加粗效果也没有正常显示，我认为这可能是个bug，因此来这里反馈。

**Comment by chbkqx** [comment]
chatnio版本3.7.2，应该是有解析的

**Comment by zmh-program** [comment]
这不是markdown 渲染的问题。公式需要用 $$ [latex] $$ 包裹。

**Comment by zmh-program** [comment]
正常来说 $$ 就是用来作为公式渲染的，但是gpt没有吐这个字，所以markdown渲染识别为正常字符。
chatnio 使用 [react-markdown](https://github.com/remarkjs/react-markdown) 和 [remark-math](https://github.com/remarkjs/remark-math) 作为 markdown 和 latex 渲染库。
使用此渲染库的还有很多软件，诸如有名的 [ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web)。

综上所述，此为通性问题，nextweb上布包裹也无法正常显示，正常做法是 使用 $$ 包裹公式。并不是软件问题，也不存在部分设备 部分情况的问题。问题在于 GPT 本身。

**Comment by zmh-program** [comment]
之前我们有在交流群上探讨过这个问题。给出的解决方案是预设中的**数学家**来快速的解决此类问题。至于要是想说 “ nextweb 为什么不需要自己手动加预设？” 不妨自己看看 nextweb 的源码，里面有一个内置通用的系统预设
```ts
export const DEFAULT_SYSTEM_TEMPLATE = `
You are ChatGPT, a large language model trained by OpenAI.
Knowledge cutoff: {{cutoff}}
Current model: {{model}}
Current time: {{time}}
Latex inline: $x^2$ 
Latex block: $$e=mc^2$$
`;
```

位置帮你找到了，[~/app/constant.ts](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/cf50299b142a40d1b043f0b3ceb3cc6c4c5b249d/app/constant.ts#L83)

我曾问过作者，这个通用预设类似于能使 ChatGPT 认识到自己是 ChatGPT。最近 nextweb 也加了一个关闭此内置预设的功能。

**Comment by zmh-program** [comment]
至于为什么 chatnio 无法复刻这条道路，应该不说你也会明白了。这就是 chatnio 自身聚合的因素。

> You are ChatGPT, a large language model trained by OpenAI.

本段提示具有错误引导，在其他非 ChatGPT 模型会被错误引导为 ChatGPT。同时也有国内大模型（我就不点名谁了）直接屏蔽 ChatGPT 这个词的存在。同时，为了不必要的麻烦（比如其他模型不支持 system 预设，入参需要user和bot交替，等诸多模型兼容性问题，以及系统预设也是会有额外 token 消耗），chatnio不适合这样写，之后也不会这样写。

**Comment by zmh-program** [comment]
解决方案：**预设设置** > **数学家**

**Comment by zmh-program** [comment]
综上所述，不是软件问题，不是兼容问题。
