### ISSUE TITLE
[Improve] 提供后台用户管理设置订阅详细信息和操作

### ISSUE THREAD

**Issue by hfoi589** [Deeptrain-Community/chatnio#190]
管理员在用户信息列表，设置用户等级后，实际上该用户等级并未改变，仪表盘中用户等级统计也显示该用户等级调整并未生效

**Comment by AnnaStreeter** [comment]
这个我知道，没有设置订阅时长或者已经过期，肯定不会显示的

**Comment by AnnaStreeter** [comment]
有个`赠送订阅`，输入订阅月数即可

**Comment by hfoi589** [comment]
> 有个`赠送订阅`，输入订阅月数即可

不是，我试了还是不行，用户列表的“是否订阅”，还是否
![Uploading WX20240510-223029@2x.png…]()

**Comment by hfoi589** [comment]
而且送出去的订阅月数，也收不回来了

**Comment by hfoi589** [comment]
![WX20240510-223029@2x](https://github.com/Deeptrain-Community/chatnio/assets/39638586/12b82f09-5e89-4fa1-bfe8-268d1c1a9c31)

**Comment by hfoi589** [comment]
![WX20240510-224212@2x](https://github.com/Deeptrain-Community/chatnio/assets/39638586/d9eeaa36-0c25-4e13-af6a-adc65ab10315)
调整为普通用户后，订阅还在，也收回不了

**Comment by hfoi589** [comment]
> Referen

我知道啦，先调整等级，在赠送订阅，就会导致是否订阅无法转变为是。
如果是先赠送订阅再调整等级，则无问题，

**Comment by zmh-program** [comment]
后台用户管理里的赠送订阅这块应该是有些问题，不是很完美，我后期打算把赠送月份改成日历组件，并与订阅等级合并至一个Dialog中，同时列表显示订阅到期时间。

**Comment by zmh-program** [comment]
![091560f88e53a3f98f5e2988dc0650df](https://github.com/Deeptrain-Community/chatnio/assets/112773885/ef9c3929-b300-43db-b664-75a933578b69)
![6b4244170aac7d574748d3cb7f22e687](https://github.com/Deeptrain-Community/chatnio/assets/112773885/404c484c-376c-4a35-a941-c2e6f4ddda93)
![d9c838fba8bc180207792aa4a904e70a](https://github.com/Deeptrain-Community/chatnio/assets/112773885/cfac1e30-02f3-4244-a3c5-24f570d7a750)


商业版已经支持, Waiting for @XiaomaiTX 下放开源版。
> commit: https://github.com/Deeptrain-Community/chatnio-pro/commit/2c0bf0d51e71f4b5024ec24f5b48a9f3f2e2556b

**Comment by XiaomaiTX** [comment]
已下放，等待容器更新
commit:   [6e8c33](https://github.com/Deeptrain-Community/chatnio/commit/6e8c33f1a2948e2ff74e9474a69677ccb3dd38f0)
