### ISSUE TITLE
编译完成了，数据库也连正确，但是日志一直在报错

### ISSUE THREAD

**Issue by ersaijun** [Deeptrain-Community/chatnio#192]
![image](https://github.com/Deeptrain-Community/chatnio/assets/16569525/2b54a99c-f45e-4add-8d5f-cb14c9aacdcf)

按照提示搭建了一个自用的网站 ai.omegaxyz.cn
配置没啥问题，模型也对接正确，但是后台日志一直在报错，每天都生成三四个文件

什么原因呢，现在是每隔一段时间手动删除掉文件

**Comment by AnnaStreeter** [comment]
你的mysql无法连接，密码错误
