### ISSUE TITLE
Key 中转支持 `function_calls`

### ISSUE THREAD

**Issue by RayGicEFL** [Deeptrain-Community/chatnio#20]
如题，中转key的时候可否带上`function`参数，否则比如 lobechat 的插件功能都无法使用  
参考 https://platform.openai.com/docs/guides/function-calling

**Comment by zmh-program** [comment]
支持 `tools_calling`，fc已经被deprecated。

**Comment by RayGicEFL** [comment]
ok，等他们那边换tool吧

**Comment by zmh-program** [comment]
https://platform.openai.com/docs/api-reference/chat/create#chat-create-function_call
