### ISSUE TITLE
[Option] Web UI 默认隐藏工具栏选项

### ISSUE THREAD

**Issue by sunqiuming526** [Deeptrain-Community/chatnio#201]
如图所示, 对于小屏幕的终端底部的工具栏会占用很多空间, 并且手动隐藏后每次重启后依旧会默认打开。

个人感觉只有"对话"用到的频率最高, 其余的选项使用频率并不高, 所以建议可以默认隐藏工具栏。

谢谢!

<img width="602" alt="Snipaste_2024-05-25_13-56-00" src="https://github.com/Deeptrain-Community/chatnio/assets/21358630/3780478d-3a2a-4664-84ec-fb37eaf443f0">

**Comment by zmh-program** [comment]
默认应该不可能，但是可以设置里设置选项开启时是否默认关闭footer

**Comment by zmh-program** [comment]
已于 v4.4.5 支持
![image](https://github.com/Deeptrain-Community/chatnio/assets/112773885/fdfe5ebd-f0a2-408d-af12-edd970290fab)

**Comment by Pevernow** [comment]
> 已于 v4.4.5 支持 ![image](https://private-user-images.githubusercontent.com/112773885/335776600-fdfe5ebd-f0a2-408d-af12-edd970290fab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMzY4NTIsIm5iZiI6MTcyOTMzNjU1MiwicGF0aCI6Ii8xMTI3NzM4ODUvMzM1Nzc2NjAwLWZkZmU1ZWJkLWYwYTItNDA4ZC1hZjEyLWVkZDk3MDI5MGZhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxMTE1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDFkYjUwOWZlMjg3Y2ZlNDZlMjJlYmFhZThiNzI1Y2Y3YjlmMTkwOWFmYmIzMzZkYjMzNDhjMjViMTMyMzRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CInt2b1fy1ujzS5YSik99inLgB3HenvkihKpiTJ8iGM)

@zmh-program 没看到v4.4.5阿？

**Comment by AnnaStreeter** [comment]
> > 已于 v4.4.5 支持 ![image](https://private-user-images.githubusercontent.com/112773885/335776600-fdfe5ebd-f0a2-408d-af12-edd970290fab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMzY4NTIsIm5iZiI6MTcyOTMzNjU1MiwicGF0aCI6Ii8xMTI3NzM4ODUvMzM1Nzc2NjAwLWZkZmU1ZWJkLWYwYTItNDA4ZC1hZjEyLWVkZDk3MDI5MGZhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxMTE1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDFkYjUwOWZlMjg3Y2ZlNDZlMjJlYmFhZThiNzI1Y2Y3YjlmMTkwOWFmYmIzMzZkYjMzNDhjMjViMTMyMzRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CInt2b1fy1ujzS5YSik99inLgB3HenvkihKpiTJ8iGM)
> 
> @zmh-program 没看到v4.4.5阿？
> 

v4是商业版，您可以联系我购买～
