### ISSUE TITLE
Open-source VS Pro questions

### ISSUE THREAD

**Issue by asaxinglm** [Deeptrain-Community/chatnio#202]
I just discovered this project and I congratulate you because it looks really promising 👏

But I have some doubts, I try to expose them here.

1. What are the differences between the open-source version and the Pro version?
2. Is the code for the Pro version (I assume it is paid) still accessible for making customizations?
3. In the open-source version I can't find so many features described in the README, such as the whole part about the dashboard, user management, payments, etc.
4. In the open-source version I can't find where to set the API keys to enable the various providers.

Thanks in advance

**Comment by zmh-program** [comment]
👋 Maybe the following answers will help you:
 1. please check https://chatnio.com for more information (sorray that paypal payment method is not currently supported)
 2. u can also making customizations by way of setting up custom css/js.
 3. & 4. All features of README are taken from the open source version. Please explore to answer questions on your own. (eg. Admin and Api Settings in the avatar dropdown menu)
