### ISSUE TITLE
关于发送键默认值

### ISSUE THREAD

**Issue by V-arc** [Deeptrain-Community/chatnio#204]
PC端默认为 `Enter`，移动端默认 `Ctrl + Enter` 是否更好？

**Comment by zmh-program** [comment]
这个方案很不错的，#75 也有相关讨论：支持后台自定义对于用户级别的偏好设置 我认为功能冗余，但是此方案我觉得目前这是最佳方案。

**Comment by zmh-program** [comment]
bug report: desktop version is in reverse order [need fix] @Sh1n3zZ

**Comment by zmh-program** [comment]
refer: https://github.com/Deeptrain-Community/chatnio-pro/commit/1fc4f5bf6b948c75b0b8e2b45320ef8c46da846f

**Comment by XiaomaiTX** [comment]
refer: https://github.com/Deeptrain-Community/chatnio/commit/b78e8fe2e992830a49c8c2fec61d88f4fbab6aaf

Bump version to 3.11.1

Closed this issue
