### ISSUE TITLE
关于同一个会话中更换模型回答之后刷新页面又变为最初的模型

### ISSUE THREAD

**Issue by dqzboy** [Deeptrain-Community/chatnio#205]
在同一个会话里面，比如我第一次对话使用的是gpt3.5，中间切换为gpt4继续对话，但是我重新刷新页面或者重新打开网站，这个会话的模型都会切换为第一次进行对话时使用的模型，而不是上一次进行对话时使用的模型。不知道是项目最初的逻辑设计就是这样的还是属于BUG

**Comment by AnnaStreeter** [comment]
看代码逻辑，每个对话会存储一个 `model` 字段，首次提问创建一条conversation, 视为主模型，后续切换模型则切换为附模型。
后续请求时将返回主模型并切换至主模型。

**Comment by dqzboy** [comment]
> 看代码逻辑，每个对话会存储一个 `model` 字段，首次提问创建一条conversation, 视为主模型，后续切换模型则切换为附模型。 后续请求时将返回主模型并切换至主模型。

好的明白了，但是这导致个问题，就是刷新页面或者重新打开页面点击此会话时，加载很耗时

**Comment by AnnaStreeter** [comment]
> > 看代码逻辑，每个对话会存储一个 `model` 字段，首次提问创建一条conversation, 视为主模型，后续切换模型则切换为附模型。 后续请求时将返回主模型并切换至主模型。
> 
> 好的明白了，但是这导致个问题，就是刷新页面或者重新打开页面点击此会话时，加载很耗时

和这个有啥关系，这是SQL查询导致的吧，而且也没有多耗时

**Comment by AnnaStreeter** [comment]
我是用内网 Nas+K8s搭的，目测延时几乎没影响，在5ms以内
