### ISSUE TITLE
关于模型未说完话却总是断字然后一直转圈

### ISSUE THREAD

**Issue by qwq202** [Deeptrain-Community/chatnio#206]
![image](https://github.com/Deeptrain-Community/chatnio/assets/146629280/1385d3e5-79e4-462d-96ac-27473eebd11f)

**Comment by qwq202** [comment]
我注意到你们的官网也是这样的情况400字左右的时候就断字了
![image](https://github.com/Deeptrain-Community/chatnio/assets/146629280/6b5c65c8-8b7e-45e3-90bb-4a27e2cce2a0)
![image](https://github.com/Deeptrain-Community/chatnio/assets/146629280/40691998-5682-41b5-90d6-0cbfd7ede76e)
![闲聊](https://github.com/Deeptrain-Community/chatnio/assets/146629280/b840e785-5594-4178-bcab-9e51cd0486fc)
正常来说是这样的

**Comment by AnnaStreeter** [comment]
上游卡顿这是你上游问题啊，你是怎么想到提issue的
