### ISSUE TITLE
偶发性无规律报错messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row (type: invalid_request_error)

### ISSUE THREAD

**Issue by ViperGash** [Deeptrain-Community/chatnio#209]
![image](https://github.com/Deeptrain-Community/chatnio/assets/12899913/d25c08e1-9c76-46f9-a79c-81b5a3795013)
最近总是遇到这个提示。claude和gpt都会遇到。api渠道都是自己走官方的。没有中转。

messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row (type: invalid_request_error)

这个是当时的日志。

{"role":"assistant","content":"这张图片展示了一个知识图谱(Knowledge Graph)。它包含了多个相互连接的节点,每个节点代表一个概念或实体。主要内容如下:\n\n1. 中心节点是\"Tesla Model 3\",与多个其他节点相连。\n\n2. 地理位置相关的节点:\n   - Fremont\n   - Palo Alto\n   - California\n   - Hollywood\n   - Paris\n   - France\n\n3. 公司和品牌:\n   - Tesla\n   - Renault\n\n4. 人物:\n   - Isabelle Adjani\n   - Macron\n   - Matthew McConaughey\n\n这些节点通过线条相互连接,表示它们之间存在某种关系。例如,Tesla Model 3与Fremont、Palo Alto和California相连,可能表示这款车的生产或设计地点。\n\n图的右上角标注了\"Knowledge Graph\"(知识图谱)字样,说明这是一个知识图谱的示例。\n\n这种图谱结构可以直观地展示不同概念之间的关联,有助于理解复杂的信息网络和关系。"},{"role":"user","content":[{"type":"text","text":"你能推荐一个通过代码自动生成知识图谱的方式/平台吗，并在该种方式/平台中复现我给你的知识图谱"}]},{"role":"assistant","content":"messages: roles must alternate between \"user\" and \"assistant\", but found multiple \"user\" roles in a row (type: invalid_request_error)"},{"role":"user","content":[{"type":"text","text":"你能推荐一个通过代码自动生成知识图谱的方式/平台吗，并在该种方式/平台中复现我给你的知识图谱"}]}],"max_tokens":2000,"model":"claude-3-5-sonnet-20240620","stream":true,"temperature":0.6,"top_p":1,"top_k":5}
[DEBUG] - [2024-06-21 10:50:58] - [sse] request failed with status: 400 Bad Request
response: {"type":"error","error":{"type":"invalid_request_error","message":"messages: roles must alternate between \"user\" and \"assistant\", but found multiple \"user\" roles in a row"}}
[WARNING] - [2024-06-21 10:50:58] - [channel] caught error messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row (type: invalid_request_error) for model claude-3-5-sonnet-20240620 at channel claude
[INFO] - [2024-06-21 10:50:58] - [channel] channels are exhausted for model claude-3-5-sonnet-20240620
[WARNING] - [2024-06-21 10:50:58] - messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row (type: invalid_request_error) (model: claude-3-5-sonnet-20240620, client: xxxxx)

**Comment by ViperGash** [comment]
4o的错误发生的时候还没开启调试模式。所以等下次出现再补充。目前只有claude的。

**Comment by AnnaStreeter** [comment]
chatnio 什么版本

**Comment by zmh-program** [comment]
latest 无法复现，请更新版本

**Comment by zmh-program** [comment]
TIP: 如果你更新至最新版后仍然通过对接官方接口报错，请 Reopen 此 issue
