### ISSUE TITLE
Gemini接入

### ISSUE THREAD

**Issue by hqzh** [Deeptrain-Community/chatnio#21]
Gemini接入有考虑接入吗？

**Comment by zmh-program** [comment]
solved.

<img width="477" alt="aa0814cac2c647191dd4531dc56def5b" src="https://github.com/Deeptrain-Community/chatnio/assets/112773885/690b808b-d081-4b09-974c-cd72e3d5f536">
<img width="479" alt="8638c9ac0c1bf834df6ae4d4be51bc75" src="https://github.com/Deeptrain-Community/chatnio/assets/112773885/3d189ea9-b0c4-4bab-9528-9768fb40848c">

<img width="672" alt="37e3722892968f140656d360f12ebae1" src="https://github.com/Deeptrain-Community/chatnio/assets/112773885/3afa0fe0-9f4d-4ac1-a7a3-a2790803dd5e">

**Comment by zmh-program** [comment]
Tip: gemini pro vision 不支持多轮对话
