### ISSUE TITLE
单个附件大小不能超过25MB

### ISSUE THREAD

**Issue by gmksbk** [Deeptrain-Community/chatnio#210]
上传附件的时候如果大于25MB就会有提示：文件过大  单个文件大小不能超过25MB。只能分割上传。
直接访问blob，上传文件正常没有大小限制。请问这是什么原因？是否需要在chatnio追加环境变量？

**Comment by Sh1n3zZ** [comment]
Hi,

是 chatnio 的限制，见：

https://github.com/Deeptrain-Community/chatnio/blob/0ddd2d2a894ae4d60e2eb1d64075c75eaaae3d28/app/src/components/FileProvider.tsx#L35

Regards,
Junhai Deng

**Comment by gmksbk** [comment]
> Hi,
> 
> 是 chatnio 的限制，见：
> 
> https://github.com/Deeptrain-Community/chatnio/blob/0ddd2d2a894ae4d60e2eb1d64075c75eaaae3d28/app/src/components/FileProvider.tsx#L35
> 
> Regards, Junhai Deng

感谢

**Comment by Sh1n3zZ** [comment]
Hi,

目前暂时不支持通过使用“环境变量”的方式进行修改，未来近期可能也不会对这部分内容做出修改，评估后可能会在后台添加此功能。
建议您现在可以通过 fork 本仓库后修改此行代码并按照 README 中的步骤进行手动编译部署的形式以实现您在此 issue 中所提到的“更改上传文件大小最大值”同时便于后续与本仓库进行 sync update

Best Regards,
Junhai Deng

**Comment by gmksbk** [comment]
> Hi,
> 
> 目前暂时不支持通过使用“环境变量”的方式进行修改，未来近期可能也不会对这部分内容做出修改，评估后可能会在后台添加此功能。 建议您现在可以通过 fork 本仓库后修改此行代码并按照 README 中的步骤进行手动编译部署的形式以实现您在此 issue 中所提到的“更改上传文件大小最大值”同时便于后续与本仓库进行 sync update
> 
> Best Regards, Junhai Deng

感谢
