### ISSUE TITLE
附件或者图片能否使用base64实现

### ISSUE THREAD

**Issue by a8851625** [Deeptrain-Community/chatnio#215]
如题

少一个服务，部署起来也简单些

**Comment by Sh1n3zZ** [comment]
Hi,

chatnio-blob-service 项目附带支持 base64 的选项，不需要其他依赖、支持使用 vercel 进行一键部署
具体请查看 https://github.com/Deeptrain-Community/chatnio-blob-service/ 项目的 README.md

Regrads,
Junhai Deng

**Comment by AnnaStreeter** [comment]
提问题前建议看文档

**Comment by Sh1n3zZ** [comment]
Hi,

较为冗余，建议使用 vercel 一键快速部署。

Regards,
Junhai Deng

**Comment by a8851625** [comment]
好的，确实是支持，没看清楚；抱歉，不过内容貌似不全：

{"model":"qwen","messages":[{"role":"user","content":"hi"},{"role":"assistant","content":"Hi! How can I help you today? "},{"role":"user","content":"hi"},{"role":"assistant","content":"Hi! How can I assist you today?"},{"role":"user","content":"```file\n[[20240618-104928.jpeg]]\ndata:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA ...\n```\n\n图片的内容是啥？"}],"max_tokens":2000,"stream":true,"presence_penalty":0,"frequency_penalty":0,"temperature":0.8,"top_p":1}

**Comment by zmh-program** [comment]
hey there, your model `qwen` is not a vision-ability common model, you should using the models mapping or other models like `gpt-4-turbo`, `claude-3-opus` and so on.
