### ISSUE TITLE
支持searxng

### ISSUE THREAD

**Issue by TerLand0berver** [Deeptrain-Community/chatnio#216]
支持一下searxng,类似dify

**Comment by zmh-program** [comment]
商业版已率先支持 feat: support searxng, Waiting for @Sh1n3zZ 下放开源版。

> todo:
> https://github.com/Deeptrain-Community/chatnio-pro/commit/1e3b436ac15ac33022c6294333c353eaea982666
> https://github.com/Deeptrain-Community/chatnio-pro/commit/f6204a0567a4360095605d6130875938fd83e3f5

**Comment by Sh1n3zZ** [comment]
Hi,

Done, maybe there are issues to optimize later.

Regards,
Junhai Deng
