### ISSUE TITLE
更易操作的用户管理

### ISSUE THREAD

**Issue by TerLand0berver** [Deeptrain-Community/chatnio#219]
首先,用户显示应该是从后往前,新注册的显示在前
对用户实现更多分类,例如是否订阅筛选,付费金额筛选,注册日期筛选

**Comment by TerLand0berver** [comment]
后台管理更易操作,例如在渠道设置子目录下,点击渠道设置回到渠道设置主目录

**Comment by zmh-program** [comment]
商业版已支持

![9cecf603049138f83b2fcca5d801930a](https://github.com/Deeptrain-Community/chatnio/assets/112773885/d65628ae-6e7d-4ffd-884f-1a92b1e6b01b)

![ab0c6d8355d41273dfa171e07f5995f0](https://github.com/Deeptrain-Community/chatnio/assets/112773885/a8b6f6f4-d056-4954-8468-088a94ec05c6)
