### ISSUE TITLE
模型提供商支持提议 | Model Provider Support Proposals

### ISSUE THREAD

**Issue by zmh-program** [Deeptrain-Community/chatnio#222]
Chat Nio 目前已经集成了各大模型供应商，为跟进新模型发展，我们集中此 issue 以记录大家对于新模型服务商的需求和优先级情况

提交未支持的新供应商格式：
**供应商名+API 文档+介绍**

已支持的供应商模型更新格式:
**新模型+API 文档**

我们将根据评论下方表情中的“👍（大拇指）”数作为**优先级**决定支持的先后程度

**Comment by zmh-program** [comment]
NovelAI / novelai.net / Image Generation

**Comment by zmh-program** [comment]
Baidu ERNIE / https://cloud.baidu.com/doc/WENXINWORKSHOP/s/flfmc9do2

**Comment by zmh-program** [comment]
AWS Bedrock / https://aws.amazon.com/cn/bedrock

**Comment by zmh-program** [comment]
Google Vertex AI / https://cloud.google.com/vertex-ai

**Comment by zmh-program** [comment]
Cloudflare AI / https://ai.cloudflare.com

**Comment by zmh-program** [comment]
01.AI / https://01.ai

**Comment by zmh-program** [comment]
Cohere (Command R) / https://cohere.com/command

**Comment by zmh-program** [comment]
OpenRouter / https://openrouter.ai

**Comment by zmh-program** [comment]
Step / https://www.stepfun.com

**Comment by xiaoheiCat** [comment]
Coze 扣子 / https://www.coze.cn/docs/developer_guides/chat_v3 & https://www.coze.com/docs/developer_guides/chat_v3，/ Coze 扣子是字节旗下的 AI Bot 开发平台，目前支持部分用户将自己制作的 Bot 发表为 API 进行调用。注意：Coze 扣子分为国版 (coze.cn) 与国际版 (coze.com)，相互之间账号与制作的 Bot 不通用，接入时请让用户确认 API 域名。

**Comment by 360troubleWind** [comment]
dify的应用中的API，文档将会在会在dify用户的应用内部展现
![image](https://github.com/user-attachments/assets/3f043a5b-2215-4ba7-90c9-caf187de6711)
dify官方网址：[dify](https://dify.ai/)

**Comment by acleverfreebird** [comment]
支持智谱清影制作视频大模型
[API文档](https://maas.aminer.cn/dev/api#cogvideox)
模型名CogVideoX

**Comment by zydmtaichi** [comment]
Stable Diffusion web UI / [API文档](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API)
A web interface for Stable Diffusion, implemented using Gradio library.

**Comment by shuyaoyimei** [comment]
siliconflow [API DOC](https://docs.siliconflow.cn/api-reference/chat-completions/chat-completions) + Based on an excellent open-source foundational model, we provide cost-effective GenAI services, similar to Groq Service.

**Comment by jasonhp** [comment]
[Novita AI](https://novita.ai/model-api/product/llm-api)
Novita is the go-to inference platform for AI developers seeking a low-cost, reliable, and simple solution for shipping AI models.
