### ISSUE TITLE
按钮名称错误

### ISSUE THREAD

**Issue by bmwa0813** [Deeptrain-Community/chatnio#228]
![微信截图_20240717002306](https://github.com/user-attachments/assets/7d5b8588-856f-4e29-8f7c-557c5b50558c)
此处实际为“重新回答”

**Comment by zmh-program** [comment]
fixed. bug created at 2024/7/17 (https://github.com/Deeptrain-Community/chatnio-pro/commit/32979fb45ff68045f14b4a740c42d02d30d2d997).
