### ISSUE TITLE
MJ图片无法存到服务端

### ISSUE THREAD

**Issue by ws02589111** [Deeptrain-Community/chatnio#230]
参考了该问题#157， 多次重新设置了，目前dalle的图片可以正常存储，但是mj的图片依然显示的原始地址
![image](https://github.com/user-attachments/assets/e330a392-6ed3-43aa-89b5-356b8357157e)

**Comment by ws02589111** [comment]
补充配置文件信息
![image](https://github.com/user-attachments/assets/fc0ea546-b5f2-4964-8972-0e2d2cd336e2)

**Comment by zmh-program** [comment]
为什么存储图片选项的问号提示呢，存储图片就是 DALLE 格式专有，Midjourney 渠道的存储在哪(反代、存储桶)应该是由 Midjourney Proxy 配置的，不会考虑再重写轮子。
