### ISSUE TITLE
gpt系列只有gpt-4o模型可以用了吗？

### ISSUE THREAD

**Issue by skywolf123** [Deeptrain-Community/chatnio#231]
我在主站尝试了多个gpt系列的模型，都返回request failed with status code: 403，还包括Azure的都试了，只有gpt-4o可以正常使用

**Comment by zmh-program** [comment]
看模型市场，主站 `gpt-4`, `gpt-4-turbo` 目测都可以，而且这里是开源软件的 issue，软件反馈不应在开源项目处反馈，我并不负责主站的运营，我本无权回答/复现/解决此问题，请在社区群/微信客服中询问。
