### ISSUE TITLE
用户账号界面的账号ID

### ISSUE THREAD

**Issue by bmwa0813** [Deeptrain-Community/chatnio#234]
[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整浏览项目 README 和项目文档并未找到解决方案
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我将以礼貌和尊重的态度提问，不得使用不文明用语 (包括在此发布评论的所有人同样适用, 不遵守的人将被 block)
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
能否隐藏用户的账号管理界面中，昵称下方的账号ID，会在一定程度上暴露站点经营状态，另外前期数值很小也可能影响用户转化。
**相关截图 (如果有)**

**Comment by zmh-program** [comment]
很正常吧, 基本上都有,  new api等等

**Comment by zmh-program** [comment]
并且id还有助于锁定是哪个用户，不然多个用户名一样的不看id做操作什么的如果重名了不知道是哪个

**Comment by bmwa0813** [comment]
能否改为某种不规则序号

**Comment by zmh-program** [comment]
id是mysql的`PRIMARY KEY`, 为了这个再损耗性能没必要, 如果真想去掉用主题设置里写 css 隐藏掉

**Comment by zmh-program** [comment]
还有隐藏 id 也治标不治本啊，一看群里多少人一打眼就能看出来，还是得往实里发展，我只能说这个需求不太会考虑实现的。

**Comment by bmwa0813** [comment]
okk
