### ISSUE TITLE
Claude模型多轮对话后报错

### ISSUE THREAD

**Issue by SHLE1** [Deeptrain-Community/chatnio#237]
[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整浏览项目 README 和项目文档并未找到解决方案
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我将以礼貌和尊重的态度提问，不得使用不文明用语 (包括在此发布评论的所有人同样适用, 不遵守的人将被 block)
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
使用`claude-3-5-sonnet`模型多轮对话后会出现报错，稳定复现，日志如下
```
[DEBUG] - [2024-07-24 15:35:15] - [sse] request failed with status: 400 Bad Request
response: {"error":{"code":"error","message":"Provider API error: messages: first message must use the \"user\" role (request id: 202407241536201035967397AHrZz4L)","type":"invalid_request_error"}}
[WARNING] - [2024-07-24 15:35:15] - [channel] caught error Provider API error: messages: first message must use the "user" role  (type: invalid_request_error) for model claude-3-5-sonnet-20240620 at channel one-api
[INFO] - [2024-07-24 15:35:15] - [channel] channels are exhausted for model claude-3-5-sonnet-20240620
[WARNING] - [2024-07-24 15:35:15] - Provider API error: messages: first message must use the "user" role  (type: invalid_request_error) (model: claude-3-5-sonnet-20240620, client: ***
```

**相关截图 (如果有)**
<img width="1414" alt="image" src="https://github.com/user-attachments/assets/1cc4a61c-7313-486a-8670-011f293d7cf3">

**Comment by zmh-program** [comment]
是不是上游接的中转

**Comment by SHLE1** [comment]
[oneapi](https://github.com/MartialBE/one-api)接的vertex

**Comment by zmh-program** [comment]
那就是了 one的bug

**Comment by zmh-program** [comment]
duplicate #227

**Comment by SHLE1** [comment]
切换成anthropic渠道后使用[oneapi](https://github.com/MartialBE/one-api)提供的`/claude`接口，测试后解决了此问题。感谢

**Comment by SHLE1** [comment]
使用[oneapi](https://github.com/MartialBE/one-api)提供的`/claude`接口，

**Comment by zmh-program** [comment]
好的
