### ISSUE TITLE
gmail邮箱不支持注册吗

### ISSUE THREAD

**Issue by ersaijun** [Deeptrain-Community/chatnio#241]
[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整浏览项目 README 和项目文档并未找到解决方案
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我将以礼貌和尊重的态度提问，不得使用不文明用语 (包括在此发布评论的所有人同样适用, 不遵守的人将被 block)
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
gmail邮箱，收不到验证码

**复现步骤**

**预期结果**

**日志信息**

**相关截图 (如果有)**

**Comment by zmh-program** [comment]
。。你说是就是吧
