### ISSUE TITLE
同步上游模型的问题

### ISSUE THREAD

**Issue by wx-11** [Deeptrain-Community/chatnio#242]
点击"对接上游" 获取`/v1/models`报错,才发现我内网渠道是前端请求,没过后端.

- 这样对内网地址,国外上游,白名单上游等都有影响,毕竟以后实际请求是后端
- 所以想问问`获取模型接口能不能也过后端`?

另外有一个建议,不知道能否考虑一下?

- 在修改渠道的地方,直接加一个按钮获取列表,这样同步新模型不用重新对接上游创建一个新的渠道.可以直接修改同步

很好的项目,感谢开发.已支持商业版.要是太麻烦不采纳也没问题.按你们的意思来

**Comment by zmh-program** [comment]
🤔现在应该没有想法支持 可以付费支持一下此功能

**Comment by zmh-program** [comment]
🤔现在应该没有想法支持 可以付费支持一下此功能
