### ISSUE TITLE
支持内置模型在线率 Uptime

### ISSUE THREAD

**Issue by zmh-program** [Deeptrain-Community/chatnio#25]
开启监控后，将对所有人提供“自定义市场模型”内模型各个时间的uptime情况，
类似于 uptime kuma 等，但是 kuma 这些需要每次请求都要消耗配额。
chatnio 内置的思路是分析每一次请求是否 error 的情况，
筛选出去超上下文等其他非异常报错情况，进行监控。

此功能作为长久计划。

**Comment by XiaomaiTX** [comment]
此issue已经迁移至商业版
