### ISSUE TITLE
支持利润分销功能

### ISSUE THREAD

**Issue by zmh-program** [Deeptrain-Community/chatnio#27]
类似于 CloseAI，各大 IDC 的分销机制，
后台管理可以设置是否开启和分销利润。可支持 代理 高级代理等二级分销功能。
此类相较于 chatnio 的邀请码来说，实际产生消费，从根源解决批量注册刷余额。

作为长久计划考虑。

**Comment by XiaomaiTX** [comment]
此issue已经迁移至商业版
