### ISSUE TITLE
使用api时除chatgpt以外均不可用

### ISSUE THREAD

**Issue by chbkqx** [Deeptrain-Community/chatnio#3]
使用api时除chatgpt以外均不可用

我在使用js sdk调用时，发现model处填写除'gpt-3.5-turbo'以外的值(如gpt-4,zhipu-chatglm-lite)都会报错You don't have enough quota to use this model. please [buy](/buy) or [subscribe](/subscribe) to get more.而gpt-3.5-turbo正常使用。
setKey了，getQuota()也能正常返回，getConversations()只能返回在网页端的对话结果，点还剩190多，绝对不会不够。
经过测试，model处瞎填一个也会返回You don't have enough quota to use this model. please [buy](/buy) or [subscribe](/subscribe) to get more.。
我认为这可能是个bug，所以搁这反馈一下。
测试环境：安卓11，webview(通过via)，http正常，使用sdk编译成js。
附图片：![Uploading Screenshot_2023-10-31-19-29-22-358_bin.mt.plus.jpg…]()

**Comment by zmh-program** [comment]
收到反馈。我们正在测试。

**Comment by zmh-program** [comment]
您好，我们这边复刻不出您的问题，请问一下您是在使用哪个接口以及具体信息截图（注意打码key），谢谢。
（是key中转那个符合openai格式的接口还是chatnio私有格式）

**Comment by zmh-program** [comment]
我们似乎发现了问题的原因，稍等我们去解决

**Comment by zmh-program** [comment]
已解决。请将包更新至`1.1.6`。
