### ISSUE TITLE
提供默认设置chatnio官方站的价格设定，不考虑打折

### ISSUE THREAD

**Issue by PeterFujiyu** [Deeptrain-Community/chatnio#39]
<img width="898" alt="image" src="https://github.com/Deeptrain-Community/chatnio/assets/88922024/e57be06a-a1a2-4e46-aa99-f2c7e072632d">
 
to 

<img width="1333" alt="image" src="https://github.com/Deeptrain-Community/chatnio/assets/88922024/3e5fb702-7de0-4c4e-a652-1a45f0241308">

**Comment by zmh-program** [comment]
指 同步上游？

**Comment by PeterFujiyu** [comment]
yes

**Comment by PeterFujiyu** [comment]
可以自己选择，没有配置的模型使用官方站
