### ISSUE TITLE
支持对话中消息的编辑/删除

### ISSUE THREAD

**Issue by luxlzz6** [Deeptrain-Community/chatnio#51]
单独删除某条消息，这样上下文就可以去除无用的不需要的信息，建议发送和回复的都支持删除

**Comment by zmh-program** [comment]
chatnio 的消息存储是在服务端，而非类似于 nextweb, lobechat 存储在浏览器客户端（LocalStorage和IndexedDB），带来的好处显而易见，非常方便的跨设备同步，但是 因此在数据库中随意增删改查可能会有风险。

**Comment by zmh-program** [comment]
可以选择支持。
