### ISSUE TITLE
支持claude以openai形式调用，我想用自己买的中转

### ISSUE THREAD

**Issue by black-fruit** [Deeptrain-Community/chatnio#6]

**Comment by zmh-program** [comment]
您好，支持的
chatnio所有模型（包括`claude-2`, `claude-2-100k`）支持以openai格式调用，详情参考文档的Key中转功能：
https://docs.chatnio.net/kai-fa-zhe-zi-yuan/api-reference/key-zhong-zhuan

**Comment by zmh-program** [comment]
所有模型兼容 openai 格式

**Comment by zmh-program** [comment]
是的。所有模型。

**Comment by zmh-program** [comment]
什么意思 我没太听懂

**Comment by zmh-program** [comment]
会。但是你可以更改[前端配置](https://github.com/Deeptrain-Community/chatnio/blob/main/app/src/conf.ts)
