### ISSUE TITLE
增加内存缓冲功能,优化卡字

### ISSUE THREAD

**Issue by acte9548224** [Deeptrain-Community/chatnio#60]

**Comment by zmh-program** [comment]
准确来说，chatnio v2 是有卡字优化功能的，但后来因为一些问题，弊大于利，被删除了。

首先，我认为内存缓存后的显示的字是直接出字慢的。假设20ms一个字数，最终的显示延迟为 20ms x char，最终的结果是响应慢，在结束的时候出现一大堆缓冲区的字，造成渲染卡顿。
再为重要的一点是，比如一个base64图片，或者一个长url的图片（开启 chatnio 联网功能后常见）

```
![image](data:image/jpeg;base64,\/9j/4AAQSk...)
```

假设base64 rawcontent有几千个字符，那可能会直接导致渲染中途出现

```
![image](data:image/jpeg;base64,\/9j/4AA (省略几千字符)
```

这样的问题，以及长url等如果缓冲，渲染中途的src会直接占满一个屏幕。非常影响使用不说，浏览器渲染卡顿也是显而易见的。

再比如绘图模型，加入缓冲区会出现
```
![image](https://example.com/dalle/IsBs3oDO
```
缓冲中途显示不全的问题。

markdown 链接， html 渲染，亦有此问题。
