### ISSUE TITLE
Feature： 是否可以新增查看用户聊天记录功能

### ISSUE THREAD

**Issue by laike** [Deeptrain-Community/chatnio#65]
是否可以新增查看用户聊天记录功能

**Comment by zmh-program** [comment]
?

**Comment by zmh-program** [comment]
![4f3ec9b487055afb5b29c665806f6303](https://github.com/Deeptrain-Community/chatnio/assets/112773885/a01a52d7-a600-4b77-8463-15859196bf63)

**Comment by laike** [comment]
> ?

我可能没有说清楚 是管理员在后台可以查看特定用户的聊天记录

**Comment by zmh-program** [comment]
哦 你指这个意思啊

**Comment by zmh-program** [comment]
有什么必要么

**Comment by zmh-program** [comment]
没意义，你可以直接从数据库的 `conversation` 表查看。以此来耗费时间增加工程量大但是意义不大的功能我认为没有多大意义。

两个选择：1. 我们非常欢迎你的 PR。
2. 你需要有说法我的理由，因为目前来说我不认为这点需求是有必要的，同时这个功能工程量较大，不如直接看数据库表。如果你有合理的理由使我认为该功能有充分必要，我会正好借助我的养病期间开始写此功能。


该 issue 当前暂时以未计划关闭。

**Comment by Chenm4** [comment]
是否有计划在管理端统计当前哪个用户在哪个时间调用了，让人更清楚哪些客户是较为频繁使用的。如下图所示
![image](https://github.com/user-attachments/assets/41a2cbc3-7b18-43bc-b3a3-f4654f2a1b4c)
