### ISSUE TITLE
好像api没有embedding？

### ISSUE THREAD

**Issue by sunzhuo** [Deeptrain-Community/chatnio#66]
能不能加上啊？

**Comment by zmh-program** [comment]
摘自：README.md

![Image_1706705394034.jpg](https://github.com/Deeptrain-Community/chatnio/assets/112773885/218a2457-60f8-418c-bf80-903e6a7c9d61)

![Image_1706705399330.jpg](https://github.com/Deeptrain-Community/chatnio/assets/112773885/0d7401cf-89be-443f-bc60-7307e29db01c)

**Comment by zmh-program** [comment]
首先，我认为微调 / Embeddings 在 Chat Nio 没有任何意义，我想问你们在使用 Next Web 聊天的过程中都喜欢用纯 Embeddings 吗？

其次，Chat Nio 的架构完全以 Chat 为基，Embeddings 入参和出参完全和 Chat Completions 不同。粗略来说，兼容 Embeddings 需要增加当前后端高于一倍的代码。工程量大，没有任何意义，我也没有找到哪个地方需要 Embeddings。

**Comment by sunzhuo** [comment]
在聊天的时候也会用到啊，比如聊天中需要查询一些用户内部资料，那就会用到embedding了

**Comment by zmh-program** [comment]
长见识了，你用 nextweb 的时候都是直接看向量的？


那请问下这组向量的汉语是什么意思：
[27.5062, 89.1017]
