### ISSUE TITLE
报错的时候，直接把key暴露出来了。

### ISSUE THREAD

**Issue by tyzero** [Deeptrain-Community/chatnio#67]
gemini error: Permission denied: Consumer 'api_key:AIza**************************** has been suspended. (code: 403, status: PERMISSION_DENIED)

建议对客户端隐藏

**Comment by zmh-program** [comment]
gemini 的问题。gemini error: 后的全都为 gemini 的 error 输出

**Comment by zmh-program** [comment]
我考虑对error统一process一下
