### ISSUE TITLE
建议支持docker安装

### ISSUE THREAD

**Issue by Ruler27** [Deeptrain-Community/chatnio#7]
我部署了一下，环境一直有问题，最后还是没成功。
如果能有docker就方便了

**Comment by zmh-program** [comment]
嗯，确实是个好主意，有空支持一下

**Comment by zmh-program** [comment]
all in one 功能已经至开发结尾，docker 一键安装等一键化部署功能，k8s 分布式将在不久后支持。

**Comment by zmh-program** [comment]
finished.
