### ISSUE TITLE
支持开关注册功能

### ISSUE THREAD

**Issue by Maizi-G** [Deeptrain-Community/chatnio#72]
经询问阿里云客服，个人备案搭建这样的ai生成站点，为了合规需要仅供个人使用，不能有注册功能，希望可以新增一个启用或关闭注册的功能，非常感谢您的付出！

**Comment by zmh-program** [comment]
支持 暂停注册
![image](https://github.com/Deeptrain-Community/chatnio/assets/112773885/06186ee5-72e3-4f61-a692-39ab992d2fce)
