### ISSUE TITLE
支持后台配置默认偏好设置的 最大历史会话数，最大回复 tokens

### ISSUE THREAD

**Issue by NEPDream** [Deeptrain-Community/chatnio#75]
希望考虑支持允许管理员在后台可配置默认对话的偏好设置的初始值，或者简单点，用启动的环境变量进行配置也行。我产生这个需求的主要原因是这样的，我的用户不多，大多数都是自己的同学朋友，所以给他们是免费使用的。他们对如何正确的使用大模型是没有什么基本概念和知识的，所以，他们80%不懂上下文的概念，他们总是在一个对话框里不断的进行提问，即使其实对话的问题和上下文早已不相关了，因为是免费，所以造成我的gpt-4的key消耗的比较快。所以我希望能够在我的后台或者环境变量上进行设置一个默认值。让我可以配置用户的默认偏好设置，比如设置最大历史会话数为3。对于懂的用户，他们可以自己修改偏好设置里的内容，所以应该不影响会使用的人。
![image](https://github.com/Deeptrain-Community/chatnio/assets/31023128/fc549d86-2920-4354-a536-ec8c9d1e4cb7)

**Comment by zmh-program** [comment]
可以考虑支持偏好设置的最大历史会话数和最大 tokens，其他感觉没有什么意义
不过这个没有多少实现的重要性，我等有时间多的时候 没有其他功能的时候可以写一下

**Comment by zmh-program** [comment]
> +1，我感觉默认enter比较好。普通用户习惯

那对于没有 Ctrl 键的移动端呢

**Comment by kokojacket** [comment]
移动端不会有特别长文吧？，另外移动端一般也不会回车我感觉。

**Comment by zmh-program** [comment]
> 移动端不会有特别长文吧？，另外移动端一般也不会回车我感觉。

相反，移动端用户也会回车。
可以自定义默认，但是肯定不会默认

**Comment by kokojacket** [comment]
> > 移动端不会有特别长文吧？，另外移动端一般也不会回车我感觉。
> 
> 相反，移动端用户也会回车。
> 可以自定义默认，但是肯定不会默认

或者支持添加环境变量来把选择权交给自部署者？默认为 ctrl+Enter 就好了

**Comment by zmh-program** [comment]
> > > 移动端不会有特别长文吧？，另外移动端一般也不会回车我感觉。
> > 
> > 相反，移动端用户也会回车。
> > 可以自定义默认，但是肯定不会默认
> 
> 或者支持添加环境变量来把选择权交给自部署者？默认为 ctrl+Enter 就好了
> 


环境变量是不可能的，因为 Chat Nio 为 React 编写，不是类似于 Nextjs 这种ssr 服务端渲染的 full stack framework，因此环境变量不能在打包后执行。Nextjs至少需要无服务器环境才能搭建，而且前端渲染能力没有静态文件好。

但是对于客户端渲染一个同样可行的方法是，在public里写一个default.json, 后端更新文件, 前端动态导入，但是我认为这个没有大的必要而且工程量比较多, 所以等有空再实现。

**Comment by zmh-program** [comment]
不认同，符合习惯一般都是 CTRL+Enter，而且可以自定义发送键偏好

**Comment by AnnaStreeter** [comment]
啊，分配给我了嘛，我怎么感觉这个很没必要呢... 关了吧?

**Comment by AnnaStreeter** [comment]
用户完全可以自定义，再再后台再加东西有点本末倒置

**Comment by AnnaStreeter** [comment]
> 作者这个想法实现了吗？目前也有这个需求，本人情况和你完全一致，急需该功能

issue已经提示处理状态了，自己改源码即可，这个功能我认为没有必要

**Comment by AnnaStreeter** [comment]
@piwawa 温馨提示：好意提醒，请不要随便点emoji😁
