### ISSUE TITLE
支持使用记录，日志查看

### ISSUE THREAD

**Issue by zmh-program** [Deeptrain-Community/chatnio#77]

**Comment by zmh-program** [comment]
wip

**Comment by zmh-program** [comment]
请求日志功能完工。
![image](https://github.com/Deeptrain-Community/chatnio/assets/112773885/ae75e6c6-c689-4df3-bd7c-e900cf4b1335)
![image](https://github.com/Deeptrain-Community/chatnio/assets/112773885/45050b65-c379-43f9-9975-4f93c66fa3b4)
![image](https://github.com/Deeptrain-Community/chatnio/assets/112773885/0640ffd8-f748-4e92-a5ba-8555242b0dc6)
![image](https://github.com/Deeptrain-Community/chatnio/assets/112773885/5c1c3fd3-47eb-4c60-adf2-8bf6010824e3)
![image](https://github.com/Deeptrain-Community/chatnio/assets/112773885/5b7852f5-4bc5-4792-abb7-36fbf99f0f68)

当前为商业版独享，从 4-7 开始的 10d 后将开始向开源版下放操作。

**Comment by hfoi589** [comment]
请问下，这个功能下放开源版了吗，商用版在哪里使用呢

**Comment by zmh-program** [comment]
经过 Chat Nio 开发组考虑，请求日志功能将不再下放开源版。
