### ISSUE TITLE
对Markdown代码块输出的优化

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Deeptrain-Community/chatnio#8]
![image](https://github.com/Deeptrain-Community/chatnio/assets/109946426/c75d3d43-a2a2-433c-b1bc-a77cc09211cc)
目前的代码块有以下问题：
- 无高亮显示
- 无直接复制按钮

希望能增加以上内容

**Comment by zmh-program** [comment]
你没更新吧这是，最新版本是3.6.11

**Comment by zmh-program** [comment]
Service Worker可能在一些老的浏览器造成一系列的兼容性问题，请尝试强制删除全部缓存（不是禁用缓存或F5）并查看版本号

**Comment by JingHai-Lingyun** [comment]
好 我看看

**Comment by zmh-program** [comment]
以及高亮在 chatnio v2 就实现了吧

**Comment by JingHai-Lingyun** [comment]
高亮在3.5没有 0.0

**Comment by zmh-program** [comment]
![image](https://github.com/Deeptrain-Community/chatnio/assets/112773885/b515378f-b055-4067-8ec2-3b92ba4912f6)

**Comment by zmh-program** [comment]
哦 估计是没有`html`的css vars吧

**Comment by JingHai-Lingyun** [comment]
复制有了 v3.6.11

**Comment by zmh-program** [comment]
嘶 这个问题得移步 [react-syntax-highlighter](https://github.com/react-syntax-highlighter/react-syntax-highlighter) 😅
看样子确实是没有 `html` code 的高亮的

**Comment by zmh-program** [comment]
哦 还真没有html的highlight 我还真没注意到 倒是有htmlbars
我看看简单replace一下

![image](https://github.com/Deeptrain-Community/chatnio/assets/112773885/de5e9837-5dda-4826-b2d6-a23a6e7515e0)

**Comment by zmh-program** [comment]
.12已更新
