### ISSUE TITLE
用户管理增加分组用户管理

### ISSUE THREAD

**Issue by Xuanyu0610** [Deeptrain-Community/chatnio#84]
![Snipaste_2024-03-06_22-59-18](https://github.com/Deeptrain-Community/chatnio/assets/162407712/e15b11c1-dbe9-4c9b-8915-a1c3f81aab32)

1.root管理员可以自定义分组名称
2.用户可以通过次级管理员的邀请码注册并入该管理员组内，或root管理员手动修改
3.次级管理员可创建邀请码和兑换码，从自身账号扣除点数
4.root管理员可管理全部用户，重构当前用户管理UI

**Comment by AnnaStreeter** [comment]
此功能实现比较长并且并无太大价值，目前开源版没有此发展方向，不考虑实现，欢迎提 PR！
