### ISSUE TITLE
联网搜索无效，已部署duckduckgo-api

### ISSUE THREAD

**Issue by kokojacket** [Deeptrain-Community/chatnio#85]
联网搜索无效，已部署duckduckgo-api,似乎duckduckgo-api失效了

**Comment by zmh-program** [comment]
我这边测试没有问题，请确保格式是否填写正确 (无需填后面的path)：
```
https://example.com
```

或者测试一下你的 duckduckgo api 的https://example.com/search?q=hi 是否可以获取成功，如若不能，推荐自行排查是否为 IP 等问题或前往原项目寻求帮助 :)

**Comment by kokojacket** [comment]
您是使用docker部署的duckduckgo api还是vercel？我使用docker部署后，搜索时后台日志显示报错了。
![image](https://github.com/Deeptrain-Community/chatnio/assets/74887370/71bc92ff-902f-4872-8e42-1524805b7d62)

**Comment by zmh-program** [comment]
vercel

**Comment by zmh-program** [comment]
https://duckduckgo-api-1-seven.vercel.app/search?q=hi

**Comment by kokojacket** [comment]
好的，我去试试vercel以及别的镜像，感觉是镜像问题。

**Comment by kokojacket** [comment]
排查出来了，需要挂V。。。。。

**Comment by zmh-program** [comment]
ddg ban国内

**Comment by kokojacket** [comment]
嗯嗯，docker部署添加http proxy和https proxy可以。谢谢~

**Comment by zmh-program** [comment]
好

**Comment by kokojacket** [comment]
好像没有调用上。
查出来的热搜是17年的
![image](https://github.com/Deeptrain-Community/chatnio/assets/74887370/a4a375d5-bc51-49fd-84c9-e0bcc62e0b2d)

**Comment by zmh-program** [comment]
![Screenshot_20240307_181132.jpg](https://github.com/Deeptrain-Community/chatnio/assets/112773885/23392982-3e2a-47ba-a7ff-8f00192901d9)

**Comment by kokojacket** [comment]
![image](https://github.com/Deeptrain-Community/chatnio/assets/74887370/d8fce003-24ec-4867-abe6-d3134258bc6b)

**Comment by zmh-program** [comment]
那这就是模型问题了。

**Comment by taurusduan** [comment]
> 那这就是模型问题了。

大佬咨询一下，我这边部署了搜索，但是每次要对话几次之后才能调用搜索，不然显示的是以前的内容，不知道这个问题怎么解决啊。谢谢啊。

**Comment by zmh-program** [comment]
@taurusduan 我无法了解你的全部信息。
后台打开调试模式，打开后接下来日志将会提供程序发起所有 http 请求的全部信息。找到请求上游的报文，查看request body内是否有联网的system prompt即可知道是否向上游提供联网信息，如果提供但是不响应只能说明是模型问题。
