### ISSUE TITLE
支持 DALLE 生成图片存储于服务端

### ISSUE THREAD

**Issue by kokojacket** [Deeptrain-Community/chatnio#88]
图片不支持同步

**Comment by zmh-program** [comment]
请提供更多细节

**Comment by zmh-program** [comment]
Base64 图片我目测是可以直接同步的 因为其实file的格式是
```
     ```file
      [filename]
      [content]
     ```
```

![image](https://github.com/Deeptrain-Community/chatnio/assets/112773885/b39ce7aa-6cd7-4fc4-a09f-ec3b33cb7205)
我现在还无法复现到，这是很久之前的一个对话，图片可以被同步，如果 b64 在确保上传时就已经排查过不是格式问题后，如果确实无法同步，请提供更多细节。

**Comment by kokojacket** [comment]
昨天使用dalle3画图后的照片，今早公司打开看显示失效了。
![image](https://github.com/Deeptrain-Community/chatnio/assets/74887370/e7b0512c-795b-4b2d-b881-b5dd5b2464cc)

**Comment by zmh-program** [comment]
这不是 chatnio 的问题 这是你生成图片的链接原url失效了 chatnio不会参与存储也不应该是chatnio来做这件事

正常情况下 OpenAI DALLE 会将图片存储在这里 并且我没有复现到消失 
```
https://oaidalleapiprodscus.blob.core.windows.net
```

**Comment by kokojacket** [comment]
原来是这样，也就是实际上没有下载保存图片到服务器，而是保存了图片链接。
是否可以保存图片到服务器永久存储呢？
openai的图片链接好像确实有过期时间。

**Comment by zmh-program** [comment]
不错的提议

**Comment by zmh-program** [comment]
![image](https://github.com/Deeptrain-Community/chatnio/assets/112773885/f8fca99b-10a7-4ddb-9298-5c374aadf767)

已实现
