### ISSUE TITLE
deeptrain无法注册

### ISSUE THREAD

**Issue by black-fruit** [Deeptrain-Community/chatnio#9]
收不到邮件

**Comment by zmh-program** [comment]
首先，理论上来说这个问题不是issue吧。
请切换邮件后缀重试。

**Comment by zmh-program** [comment]
我觉得你可以提供错误信息，这么猜我是猜不出来的，以及看看是不是在垃圾邮件。

**Comment by zmh-program** [comment]
![Screenshot_20231105_170627.jpg](https://github.com/Deeptrain-Community/chatnio/assets/112773885/9f444696-78ed-4626-9159-24721a1c1d52)

**Comment by zmh-program** [comment]
腾讯云没有报故障，而且看内个图片 是可以发件的
