### ISSUE TITLE
支持邀请码/兑换码管理操作

### ISSUE THREAD

**Issue by kokojacket** [Deeptrain-Community/chatnio#90]
兑换码生成后无法管理和重新查看，无法删除
邀请码也是
用户账户无法删除
登录界面无法使用回车登录
用户自身无法更改密码（硬伤）
另外我实验注册中的一个账号，出现了无限转圈圈，完全无法使用的情况。并且无法修复，后台给点数，给订阅，都无法使用任何模型。

**Comment by kokojacket** [comment]
![image](https://github.com/Deeptrain-Community/chatnio/assets/74887370/a3d19d7f-361b-486e-8173-4c82a03acb1b)
![image](https://github.com/Deeptrain-Community/chatnio/assets/74887370/26019717-62fd-4de0-99ce-8e1a8cc7d2ff)

**Comment by zmh-program** [comment]
1. 2. 标feature
3. 可以ban用户
4. 标feature
5. 可以忘记密码
6. 确保不是上游问题？如果不是，请提供完整复现步骤，或者留下联系方式（推荐 QQ) 方便的话远程一下

**Comment by zmh-program** [comment]
已修复第 5 点

**Comment by zmh-program** [comment]
![b5f7e8ca6a7b9863b0e16a330391c055](https://github.com/Deeptrain-Community/chatnio/assets/112773885/b60ae811-201e-4f09-becd-76f86bf5c63e)

![ccdca7dd870b6152518ecc1118b9a251](https://github.com/Deeptrain-Community/chatnio/assets/112773885/ca1dbf28-84f5-4cc9-b3a4-51873f444a15)

**Comment by zmh-program** [comment]
已全部解决。
