### ISSUE TITLE
关于请求模型问题

### ISSUE THREAD

**Issue by ASDZXC535** [Deeptrain-Community/chatnio#92]
如图我选了3.5turbo却返回了3
![屏幕截图 2024-03-10 154213](https://github.com/Deeptrain-Community/chatnio/assets/149139885/bfc698d3-a6e8-4855-a61e-665f222ff2b4)

**Comment by zmh-program** [comment]
请解释你提 issue 的目的

**Comment by ASDZXC535** [comment]
> 请解释你提 issue 的目的

是不是有bug，我选了GPT3.5Turbo模型但它返回的3的模型

**Comment by zmh-program** [comment]
？这不是模型问题么 你跑到这里提issue是什么意思 你觉得难道还会加prompt？？

**Comment by AnnaStreeter** [comment]
这个issue好吊

**Comment by AnnaStreeter** [comment]
老哥这是你上游问题吧，你去lobechat试是不是一样的不就知道了

**Comment by ASDZXC535** [comment]
> 老哥这是你上游问题吧，你去lobechat试是不是一样的不就知道了

OK，我是github小白

**Comment by zmh-program** [comment]
理解

@AnnaStreeter 我知道你的意思但请友善和睦对话 不要出现这种字眼哈

**Comment by AnnaStreeter** [comment]
欧克 大佬
