### ISSUE TITLE
使用claude官方API报错400

### ISSUE THREAD

**Issue by Maizi-G** [Deeptrain-Community/chatnio#93]
request failed with status: 400 Bad Request
```json
{
  "error": {
    "message": "anthropic-version: header is required",
    "type": "invalid_request_error"
  },
  "type": "error"
}
```

**Comment by zmh-program** [comment]
![5a35fbe252ddcf73e49ebf770c679c37](https://github.com/Deeptrain-Community/chatnio/assets/112773885/046a7f78-c295-4aa1-93e6-5d12630e6f91)
