### ISSUE TITLE
优化模型市场导入模型顺序 支持拖拽

### ISSUE THREAD

**Issue by TonyNiYa** [Deeptrain-Community/chatnio#94]
目前新添加的模型会在页面最底部，手机翻阅修改的时候会翻很久，建议添加新模型的时候直接在顶部，这样修改方便

**Comment by zmh-program** [comment]
欧克 现在添加模型不止设置在顶部了 而且支持直接拖拽放置模型


![0617f91618b43e5a1452bfa7ea6d60e2](https://github.com/Deeptrain-Community/chatnio/assets/112773885/75d08bc4-8e9b-4659-9749-b0fd0c322791)
