### ISSUE TITLE
生成Markdown表格时，表格会超出对话框范围

### ISSUE THREAD

**Issue by Guikong001** [Deeptrain-Community/chatnio#95]
![image](https://github.com/Deeptrain-Community/chatnio/assets/101174061/76391eef-48ce-4e10-8a77-2eb19a86c17e)
对话框超出范围后，横向并没有翻页框。同时，靠右的发送的消息会被一起拉到聊天框外导致不可见。
尝试了几次，均出现了这种情况

**Comment by zmh-program** [comment]
OK 感谢反馈

**Comment by zmh-program** [comment]
已修复
对话和分享中都已无问题
![image](https://github.com/Deeptrain-Community/chatnio/assets/112773885/93f623d3-bc95-4d63-928b-d4ac1fd1d07b)
![image](https://github.com/Deeptrain-Community/chatnio/assets/112773885/f9514fdc-5218-45fa-92a4-9a667e824cee)
