### ISSUE TITLE
Translation: Spanish and Italian 

### ISSUE THREAD

**Issue by johnfelipe** [Deeptrain-Community/chatnio#97]
Can collaborate to string translation?

**Comment by zmh-program** [comment]
Thanks for the support! Our team is translating the English version.

**Comment by johnfelipe** [comment]
I want to contribute with spanish and Italian

**Comment by zmh-program** [comment]
Wow! We would be so grateful and thankful if that is actually possible!

**Comment by johnfelipe** [comment]
Send me link or path where is zh strings, JSON format or .Po file format I will begin...

**Comment by zmh-program** [comment]
Let's see, there's probably places like these:

- [~/README.md](https://github.com/Deeptrain-Community/chatnio/blob/main/README.md)
- [~/app/src/resources/i18n/en.json](https://github.com/Deeptrain-Community/chatnio/blob/main/app/src/resources/i18n/en.json)

The translated filename is similar to `README_IT.md`, `README_ES.md`.
That's all there is to it, thanks again for your support of this project! I'll take care of the code part, just translate the text. ❤

**Comment by zmh-program** [comment]
issue closed for now, thanks for contributing, looking forward to your pr if it's working!
