### ISSUE TITLE
不能用自己的API吗？

### ISSUE THREAD

**Issue by do02fw** [Deeptrain-Community/chatnio#98]
好多模型的API都有免费版，这里却没有，还没办法换成自己的

**Comment by do02fw** [comment]
比如gemini，通义千问等，都有免费的API额度

**Comment by zmh-program** [comment]
？自己搭建不都可以
用自己的渠道，自己设置定价

**Comment by zmh-program** [comment]
参考，这不是和 Chat Nio 和 Lobe Chat 一样的偏前端和个人化的项目，而是像 One API 一样平台提供服务的
当然可以自己用或者搭建平台对外提供服务，但是肯定需要自己搭建，One API 也不可能让自己搭建的平台让非管理员自定义key的
